import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyDe: PartnerPageCopy = {
  metaTitle: "AI MARK Partner-Netzwerk — Erschließen Sie Ihren Markt",
  metaDescription: "Vertreiben Sie KI-Produkte und digitale Lösungen mit AI MARK. Bauen Sie Kundenbeziehungen auf, erschließen Sie neue Märkte und wachsen Sie mit einem strukturierten Partnernetzwerk.",
  eyebrow: "AI MARK Partner-Netzwerk",
  title: "Bauen Sie den KI-Markt in Ihrem Land auf.",
  lead: "Vertreiben Sie echte KI-Produkte und digitale Lösungen an Unternehmen in Ihrer Region. AI MARK liefert die Technologie, Produktbereitstellung und Partnerinfrastruktur. Sie knüpfen die Kontakte und schließen die Verkäufe ab.",
  note: "50 % für Direktverkäufe · Bis zu 80 % Partnerpool über das gesamte Netzwerk · Kostenlose Teilnahme",
  primary: "Partner werden",
  secondary: "So funktioniert es",
  marketEyebrow: "Der Markt",
  marketTitle: "Ein Portfolio. Ein breiter, branchenübergreifender Markt.",
  marketLead: "Die Chance ist nicht auf eine Nische begrenzt. Unternehmen jeder Branche müssen Abläufe steuern, Kunden gewinnen, kommunizieren, digitale Präsenz sichern und Routinearbeit automatisieren.",
  market: [
    { title: "Betrieb", body: "Routinierte Kommunikation, Wissensmanagement, Koordination und Kundenanfragen erzeugen stetigen operativen Bedarf." },
    { title: "Marketing", body: "Jedes Unternehmen benötigt Reichweite, Content, Kampagnen, Kundendialoge und verlässliche Wachstumsprozesse." },
    { title: "Entwicklung", body: "Wachsende Betriebe brauchen Websites, Portale, Plattformen, Integrationen und maßgeschneiderte digitale Systeme." },
    { title: "Automatisierung", body: "Mit steigender Komplexität wächst der Bedarf an KI, automatisierten Abläufen und Systemen zur Senkung manueller Kosten." },
  ],
  marketCore: "Ihr Markt ist nicht ein einzelnes Produkt. Es ist jedes Unternehmen, das Sie erreichen können.",
  productEyebrow: "Produktportfolio",
  productTitle: "Vier Wege, echten Mehrwert für Kunden zu schaffen.",
  productLead: "Ein Partner verbindet das konkrete Geschäftsproblem eines Unternehmens mit der passenden Lösung von AI MARK, anstatt ein einzelnes Werkzeug isoliert anzubieten.",
  products: [
    { name: "AI Marketing Employee", type: "WIEDERKEHREND / KI-PRODUKT", body: "KI-natives Marketing: Recherche, Strategie, Content, Kreativerstellung, Freigabeprozess, Veröffentlichung und kontinuierliche Optimierung.", revenue: "Abonnement-Umsatz", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "WIEDERKEHREND / KI-PRODUKT", body: "Postfach für Vertrieb und Support auf Basis der unternehmenseigenen Wissensdatenbank. Qualifiziert Anfragen und übergibt nahtlos an Mitarbeiter.", revenue: "Abonnement-Umsatz", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "WIEDERKEHREND / KI-PRODUKT", body: "KI-Vertriebsagent für Beratungsdialoge, Katalogauswahl, Preisberechnungsregeln, Spezifikationen und fertige Angebote über viele Branchen.", revenue: "Abonnement-Umsatz", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROJEKT / B2B-SERVICE", body: "Websites, Portale, Webanwendungen, Schnittstellen, Automatisierung und individuelle KI-Systeme für Unternehmen mit erhöhtem Infrastrukturbedarf.", revenue: "Projekt-Umsatz", variant: "saas" },
  ],
  productCta: "Produkt ansehen",
  productionCta: "Digital Production",
  howEyebrow: "Funktionsweise",
  modelTitle: "Sie verkaufen. AI MARK liefert und betreibt.",
  modelLead: "Der Partner bildet die Marktschnittstelle. AI MARK bleibt für das vereinbarte Produkt, die Technologie und die verlässliche Umsetzung verantwortlich.",
  steps: [
    { n: "01", title: "Unternehmen ansprechen", body: "Nutzen Sie Ihr persönliches Netzwerk, Ihre Marktkenntnis oder Ihren bestehenden Kundenstamm." },
    { n: "02", title: "Bedarf analysieren", body: "Wählen Sie das Produkt oder die Dienstleistung, die das Kundenproblem exakt löst." },
    { n: "03", title: "AI MARK vorstellen", body: "Senden Sie Ihren Empfehlungslink, eine Produktseite oder leiten Sie das Gespräch persönlich ein." },
    { n: "04", title: "Verkauf abschließen", body: "Der Kunde bucht und bezahlt über Ihren getrackten Partnerkanal." },
    { n: "05", title: "AI MARK setzt um", body: "Einrichtung, Implementierung und technischer Support verbleiben vollständig bei AI MARK." },
    { n: "06", title: "Markt ausbauen", body: "Wiederholen Sie Abschlüsse, vergrößern Sie Ihren Kundenstamm und bauen Sie Ihr Partnernetzwerk auf." },
  ],
  networkEyebrow: "Partner-Netzwerk",
  networkTitle: "Zuerst persönliche Verkäufe. Danach Netzwerkumsätze.",
  networkLead: "Das Netzwerk basiert auf real bezahlten Kundenumsätzen, nicht auf reinen Registrierungen. Fünf Stufen teilen den Betrag, den der Kunde tatsächlich bezahlt hat. 80 % ist der kumulierte Partnerpool über qualifizierte Stufen — keine Einzelauszahlung an einen Partner.",
  poolHeadline: "Launch bonus: bis zu 80 % beim ersten Zahlungseingang. Verlängerungen: L1 20 % + L2 5 %.",
  poolLead:
    "Bis 31.12.2026 gilt beim ersten qualifizierten Zahlungseingang des Kunden: L1 50 % / L2 15 % / L3 7 % / L4 5 % / L5 3 % (80 %-Pool). Ab der 2. Zahlung: L1 20 % + L2 5 %. Ab 01.01.2027 erster Zahlungseingang: L1 35 % / L2 8 % / L3 4 % / L4 2 % / L5 1 % (50 %-Pool, alle fünf Stufen).",
  exampleTitle: "Bei einem provisionsfähigen Verkauf von 1.000 $ in einem 5-Stufen-Netzwerk",
  exampleRows: [
    { label: "L1 Direktpartner", value: "500 $", accent: true },
    { label: "L2", value: "150 $" },
    { label: "L3", value: "70 $" },
    { label: "L4", value: "50 $" },
    { label: "L5", value: "30 $" },
    { label: "Partnerpool (kumuliert)", value: "800 $" },
    { label: "AI Mark Anteil", value: "200 $" },
  ],
  exampleFoot: "Der Direktpartner erhält 500 $, nicht 800 $. 80 % ist die Gesamtsumme über die Stufen L1 bis L5, wenn jede Stufe qualifiziert ist.",

  renewalExampleTitle: "Derselbe Verkauf über $1.000 bei Verlängerung (ab 2. Zahlung)",
  renewalExampleRows: [
    { label: "L1 Direktpartner", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Partner-Pool (aggregiert)", value: "$250" },
    { label: "Einbehaltener Anteil AI Mark", value: "$750" },
  ],
  renewalExampleFoot: "Verlängerungen wiederholen nicht die volle fünfstufige Launch-bonus-Gitter.",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  levels: [
    { n: "L1", title: "Direktverkauf", body: "Kunden, die Sie persönlich ansprechen und gewinnen.", rate: "50 %" },
    { n: "L2", title: "Erste Netzwerkstufe", body: "Bezahlte Kundenverkäufe Ihrer direkten Partner der ersten Stufe.", rate: "15 %" },
    { n: "L3", title: "Erweitertes Netzwerk", body: "Bezahlte Verkäufe eine Ebene tiefer in Ihrer Organisation.", rate: "7 %" },
    { n: "L4", title: "Markttiefe", body: "Umsätze, die über Ihre direkten Kontakte hinausgehen.", rate: "5 %" },
    { n: "L5", title: "Maximale Tiefe", body: "Die tiefste Stufe der standardmäßigen Partnervergütung.", rate: "3 %" },
  ],
  commissionLabel: "Provision",
  commissionNote:
    "Erste Zahlung (Launch bonus bis 31.12.2026): L1 50 % / L2 15 % / L3 7 % / L4 5 % / L5 3 %. Verlängerungen ab der 2. Zahlung: L1 20 % + L2 5 %. Standard erste Zahlung ab 01.01.2027: L1 35 % / L2 8 % / L3 4 % / L4 2 % / L5 1 %.",
  statusEyebrow: "Partnerstatus",
  statusTitle: "Vier Wachstumsstufen mit AI MARK.",
  statusLead: "Der Status spiegelt die tatsächliche Geschäftsaktivität und Beziehungstiefe wider. Es ist ein Leistungsstatus, kein kaufbarer Rang.",
  statuses: [
    { tag: "START", title: "Partner", body: "Vertreiben Sie AI MARK Produkte, nutzen Sie Ihren Empfehlungslink und gewinnen Sie erste Unternehmenskunden." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Kontinuierlich aktiver Vertriebspartner mit wachsendem Kundenbestand und aufstrebendem Partnernetzwerk." },
    { tag: "MARKET", title: "Regional Partner", body: "Aufbau eines regionalen oder nationalen Marktes durch lokale Kontakte, Vertriebskoordination und Marktentwicklung." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Agenturen, Distributoren und große B2B-Vertriebskanäle. Country Partner und Strategic Partner unterliegen separaten Verträgen." },
  ],
  statusNote: "Status nach Vertriebsleistung",
  kitEyebrow: "Partner-Infrastruktur",
  kitTitle: "Was dem Partner sofort zur Verfügung steht.",
  kitLead: "Persönlicher Empfehlungslink, Partner-Dashboard, öffentliche Produktseiten, Markenressourcen und Support über Telegram, WhatsApp, Messenger und E-Mail.",
  kit: [
    "Persönlicher Empfehlungslink und Partner-ID",
    "Partner-Dashboard mit Umsatzübersicht, Provisionsnachweisen und Auszahlungshistorie",
    "Öffentliche Produktseiten, verknüpft mit Ihrem Partnercode",
    "Offizielle Markenmaterialien und verkaufsfördernde Unterlagen",
    "Lückenlose Lead-Attribution in Formularen, Partnerregistrierung und /pay",
    "Produktdaten und Spezifikationen direkt im Partner Hub abrufbar",
    "Direkter Support: Telegram, WhatsApp, Messenger und E-Mail",
  ],
  globalEyebrow: "Globale Expansion",
  globalTitle: "Wählen Sie den Markt. AI MARK stellt die Technologie.",
  globalLead: "Dasselbe erprobte Kernportfolio kann von verschiedenen Partnern in unterschiedlichsten Ländern und Branchen vertrieben werden. Die Grenze setzt allein Ihre Reichweite.",
  global: [
    "Einheitlicher technologischer Kern: dieselben bewährten KI-Lösungen weltweit im Praxiseinsatz.",
    "Lokalisierte Vertriebspräsenz: Partner passen Ansprache und Vertrieb an regionale Gepflogenheiten an.",
    "Mehrere Ertragsquellen: wiederkehrende SaaS-Lizenzen, monatliche Retainer und hochvolumige Digitalprojekte.",
    "Skalierung ohne eigenes Entwicklerteam: AI MARK übernimmt Technologiebetrieb, Implementierung und Support.",
  ],
  faqEyebrow: "FAQ",
  faqTitle: "Häufige Fragen von Partnern.",
  faq: [
    { q: "Muss ich ein Starterpaket kaufen, um Partner zu werden?", a: "Nein. Das Programm basiert auf dem Verkauf echter AI MARK Produkte und Lösungen an Unternehmen, nicht auf dem Kauf von Netzwerkpositionen. Kostenlose Registrierung." },
    { q: "Muss ich die technische Umsetzung selbst übernehmen?", a: "Nein. Der Partner konzentriert sich auf Kundenbeziehungen und den Verkauf. AI MARK übernimmt Bereitstellung, Entwicklung und technischen Support." },
    { q: "Kann ich ein eigenes Partnerteam aufbauen?", a: "Ja. Das Standardmodell unterstützt eine mehrstufige Partnerstruktur auf Basis realer Kundenzahlungen mit bis zu 5 Stufen Tiefe." },
    { q: "Erzeugen Abonnements wiederkehrende Provisionen?", a: "Ja. Die erste Zahlung nutzt Launch bonus (bis 31.12.2026) oder ab 01.01.2027 die Standard-Erstgrid. Ab der 2. Zahlung nur L1 20 % + L2 5 %." },
    { q: "Wie werde ich Regional oder Strategic Partner?", a: "Der regionale Status wird auf Basis nachgewiesener Umsätze und lokaler Marktpräsenz vergeben. Strategische Partnerschaften werden bilateral vereinbart." },
  ],
  ctaEyebrow: "Start",
  ctaTitle: "Ihr Markt. Unsere KI-Infrastruktur.",
  ctaLead: "Registrieren Sie sich als Partner, wählen Sie Ihre vertrauten Zielbranchen und starten Sie mit den Unternehmen, die Sie direkt erreichen können.",
  ctaButton: "AI MARK Partner werden",
};
