import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyEn: PartnerPageCopy = {
  metaTitle: "AI MARK Partner Network — Build Your Market",
  metaDescription: "Sell AI products and digital solutions with AI MARK. Build customer relationships, develop new markets and grow through a structured partner network.",
  eyebrow: "AI MARK Partner Network",
  title: "Build the AI market in your country.",
  lead: "Sell real AI products and digital solutions to businesses in your market. AI MARK provides the technology, product delivery and partner infrastructure. You build the relationships and the sales.",
  note: "Launch bonus until 31 Dec 2026 · Up to 80% on a client's first 3 months · Free to join",
  primary: "Become a Partner",
  secondary: "See how it works",
  marketEyebrow: "The market",
  marketTitle: "One portfolio. A broad cross-industry market.",
  marketLead: "The opportunity is not tied to one niche. Businesses everywhere need to operate, attract customers, communicate, maintain a digital presence and improve how work gets done.",
  market: [
    { title: "Operate", body: "Routine communication, knowledge work, coordination and customer requests create constant operational demand." },
    { title: "Market", body: "Every business needs visibility, content, campaigns, customer conversations and a repeatable growth process." },
    { title: "Build", body: "Growing companies need websites, portals, applications, integrations and custom digital systems." },
    { title: "Automate", body: "As processes become more complex, demand grows for AI, automation and systems that reduce manual overhead." },
  ],
  marketCore: "Your market is not one product. It is every business you can reach.",
  productEyebrow: "Product portfolio",
  productTitle: "Four ways to create value for a customer.",
  productLead: "A partner can match the customer's business problem to the right AI MARK solution instead of selling one product to one niche.",
  products: [
    { name: "AI Marketing Employee", type: "RECURRING / AI PRODUCT", body: "AI-native marketing: research, strategy, content, creative production, approval, publishing and optimization.", revenue: "Subscription opportunity", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "RECURRING / AI PRODUCT", body: "A sales and support inbox that works from a business knowledge base, qualifies requests and hands off to people when needed.", revenue: "Subscription opportunity", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "RECURRING / AI PRODUCT", body: "AI Sales Agent for customer conversations, catalog selection, pricing rules, specifications and commercial proposals across industries.", revenue: "Subscription opportunity", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROJECT / B2B SERVICE", body: "Websites, portals, applications, integrations, automation and custom AI systems for businesses that need a larger digital build.", revenue: "Project opportunity", variant: "saas" },
  ],
  productCta: "Explore product",
  productionCta: "Digital Production",
  howEyebrow: "How it works",
  modelTitle: "You sell. AI MARK delivers.",
  modelLead: "The partner is the market interface. AI MARK stays responsible for the agreed product, technology and delivery layer.",
  steps: [
    { n: "01", title: "Find a business", body: "Use your network, local market knowledge or existing customer base." },
    { n: "02", title: "Match the problem", body: "Choose the product or service that fits the business need." },
    { n: "03", title: "Introduce AI MARK", body: "Send your referral link or a live product page, or make the introduction yourself." },
    { n: "04", title: "Close the sale", body: "The customer becomes an AI MARK customer through the tracked partner channel." },
    { n: "05", title: "AI MARK delivers", body: "Setup, implementation and service execution stay on the AI MARK side." },
    { n: "06", title: "Build your market", body: "Repeat, grow your customer base and develop an eligible partner network." },
  ],
  networkEyebrow: "Partner network",
  networkTitle: "Personal sales first. Network sales next.",
  networkLead: "The network is built around paid customer sales, not registrations. Five levels share the amount the customer actually paid. 80% is the aggregate partner pool across qualified levels — not a single-partner payout.",
  poolHeadline: "Launch bonus: up to 80% on months 1–3. Renewals from month 4: L1 20% + L2 5%.",
  poolLead:
    "Until 31.12.2026, a client's first three monthly payments use L1 50% / L2 15% / L3 7% / L4 5% / L5 3% (80% pool). From month 4, renewals pay L1 20% + L2 5%. From 01.01.2027, months 1–3 use the standard 50% pool (L1 35% / L2 10% / L3 5%).",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  exampleTitle: "On a $1,000 commissionable sale with a full network",
  exampleRows: [
    { label: "L1 direct partner", value: "$500", accent: true },
    { label: "L2", value: "$150" },
    { label: "L3", value: "$70" },
    { label: "L4", value: "$50" },
    { label: "L5", value: "$30" },
    { label: "Partner pool (aggregate)", value: "$800" },
    { label: "AI Mark retained share", value: "$200" },
  ],
  exampleFoot: "The direct partner receives $500, not $800. 80% is the total across L1–L5 when every level is qualified.",
  renewalExampleTitle: "Same $1,000 sale from month 4 onward (renewal)",
  renewalExampleRows: [
    { label: "L1 direct partner", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Partner pool (aggregate)", value: "$250" },
    { label: "AI Mark retained share", value: "$750" },
  ],
  renewalExampleFoot: "Renewals do not repeat the full five-level launch bonus grid.",
  levels: [
    { n: "L1", title: "Direct sale", body: "The customer you personally introduce.", rate: "50%" },
    { n: "L2", title: "First network", body: "Paid customer sales from your first-level partners.", rate: "15%" },
    { n: "L3", title: "Extended network", body: "Paid sales one level deeper.", rate: "7%" },
    { n: "L4", title: "Market depth", body: "The network beyond direct relationships.", rate: "5%" },
    { n: "L5", title: "Maximum depth", body: "The deepest level of the standard schedule.", rate: "3%" },
  ],
  commissionLabel: "Commission",
  commissionNote:
    "Months 1–3 (launch bonus until 31.12.2026): L1 50% / L2 15% / L3 7% / L4 5% / L5 3%. Month 4+ renewals: L1 20% + L2 5%. Standard from 01.01.2027 for months 1–3: L1 35% / L2 10% / L3 5%.",
  statusEyebrow: "Partner status",
  statusTitle: "Four ways to grow with AI MARK.",
  statusLead: "Status reflects commercial activity and relationship depth. It is a business status, not a paid rank.",
  statuses: [
    { tag: "START", title: "Partner", body: "Sell AI MARK products, use your referral link, access sales resources and build your first customers." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "A consistently active seller with a growing customer portfolio and developing partner network." },
    { tag: "MARKET", title: "Regional Partner", body: "Develop a country or region through local relationships, sales activity and coordinated market growth." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Agencies, distributors and larger B2B channels. Country Partner and Strategic Partner are a separate agreement, outside the affiliate schedule." },
  ],
  statusNote: "Status by performance",
  kitEyebrow: "Partner infrastructure",
  kitTitle: "What a partner can use today.",
  kitLead: "A personal referral link, the Partner Dashboard, live product pages, brand files, and support on Telegram, WhatsApp, Messenger, and email.",
  kit: [
    "Personal referral link and Partner ID",
    "Partner Dashboard with your own sales, commissions, and recorded payouts",
    "Live product pages shared through your referral link",
    "Brand files the site already publishes",
    "Lead attribution on the contact form, partner signup, and /pay",
    "Product facts from the public pages, inside Partner Hub",
    "Public support: Telegram, WhatsApp, Messenger, and email",
  ],
  globalEyebrow: "Global expansion",
  globalTitle: "Choose the market. AI MARK provides the technology.",
  globalLead: "The same core portfolio can be introduced by different partners in different countries and industries. The market is defined by your reach and specialization.",
  global: [
    "One product engine: same core AI products deployed across international accounts.",
    "Localized commercial presence: partners adapt messaging, pricing context and customer access.",
    "Multiple monetization paths: recurring SaaS, retainers, and high-ticket digital production builds.",
    "Scale without local headcount: AI MARK manages technical delivery, infrastructure and engineering.",
  ],
  faqEyebrow: "FAQ",
  faqTitle: "Common partner questions.",
  faq: [
    { q: "Do I need to buy a starter package to become a partner?", a: "No. The program is built around selling AI MARK products and services to real businesses, not buying a position in a network. Free to join." },
    { q: "Do I have to perform the technical delivery?", a: "No. The partner manages customer relationships, introduction and sales. AI MARK is responsible for product implementation, delivery and technical support." },
    { q: "Can I build a partner team?", a: "Yes. The standard model supports a multi-tier affiliate structure tied to customer revenue, up to 5 levels deep." },
    {
      q: "Do subscription products generate recurring commissions?",
      a: "Yes. Months 1–3 use the launch bonus grid (until 31 Dec 2026) or the standard initial grid from 1 Jan 2027. From month 4, renewals pay L1 20% + L2 5% only.",
    },
    { q: "How do I become a Regional or Strategic Partner?", a: "Regional status is granted based on verified commercial volume and market leadership. Strategic and Country partnerships involve dedicated bilateral agreements." },
  ],
  ctaEyebrow: "Start",
  ctaTitle: "Your market. Our AI infrastructure.",
  ctaLead: "Join as an AI MARK partner, identify businesses with real demand, and start building your market today.",
  ctaButton: "Become an AI MARK Partner",
};
