import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyEs: PartnerPageCopy = {
  metaTitle: "Red de Partners AI MARK — Construye tu Mercado",
  metaDescription: "Vende productos de IA y soluciones digitales con AI MARK. Desarrolla relaciones comerciales, expande nuevos mercados y crece con una red estructurada de partners.",
  eyebrow: "Red de Partners AI MARK",
  title: "Construye el mercado de IA en tu país.",
  lead: "Vende productos de IA reales y soluciones digitales a empresas de tu región. AI MARK proporciona la tecnología, entrega del producto e infraestructura de partners. Tú desarrollas las relaciones y las ventas.",
  note: "50% por venta directa · Hasta 80% en recompensas totales para socios en la red · Acceso sin cuotas",
  primary: "Hacerse Partner",
  secondary: "Cómo funciona",
  marketEyebrow: "El mercado",
  marketTitle: "Un portafolio. Un amplio mercado multisectorial.",
  marketLead: "La oportunidad no está limitada a un solo nicho. Empresas de todos los sectores necesitan operar, captar clientes, comunicarse, sostener presencia digital y automatizar procesos.",
  market: [
    { title: "Operar", body: "La comunicación cotidiana, el trabajo con información, la coordinación y las solicitudes de clientes generan demanda constante." },
    { title: "Comercializar", body: "Toda empresa necesita visibilidad, contenidos, campañas, diálogo fluido con clientes y un sistema de crecimiento predecible." },
    { title: "Construir", body: "Las empresas en crecimiento necesitan webs, portales, aplicaciones, integraciones y sistemas digitales a medida." },
    { title: "Automatizar", body: "A mayor complejidad operativa, mayor demanda de IA, automatización y soluciones que reducen la carga manual." },
  ],
  marketCore: "Tu mercado no es un solo producto. Es cualquier negocio al que puedas llegar.",
  productEyebrow: "Portafolio de productos",
  productTitle: "Cuatro vías para generar valor al cliente.",
  productLead: "Un partner conecta el problema real de una empresa con la solución adecuada de AI MARK, en lugar de vender una sola herramienta a un nicho aislado.",
  products: [
    { name: "AI Marketing Employee", type: "RECURRENTE / PRODUCTO IA", body: "Marketing nativo con IA: investigación, estrategia, contenido, piezas creativas, aprobación, publicación y optimización continua.", revenue: "Ingreso por suscripción", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "RECURRENTE / PRODUCTO IA", body: "Bandeja de ventas y soporte sobre la base de conocimiento del negocio, cualifica solicitudes y deriva a personas cuando es necesario.", revenue: "Ingreso por suscripción", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "RECURRENTE / PRODUCTO IA", body: "Agente comercial de IA para diálogo con clientes, selección de catálogo, reglas de precios, especificaciones y propuestas comerciales.", revenue: "Ingreso por suscripción", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROYECTO / SERVICIO B2B", body: "Sitios web, portales, plataformas, integraciones, automatización y sistemas de IA a medida para empresas que necesitan infraestructura sólida.", revenue: "Ingreso por proyecto", variant: "saas" },
  ],
  productCta: "Explorar producto",
  productionCta: "Digital Production",
  howEyebrow: "Cómo funciona",
  modelTitle: "Tú vendes. AI MARK entrega y opera.",
  modelLead: "El partner es el contacto con el mercado. AI MARK asume la responsabilidad del producto acordado, la tecnología y el despliegue técnico.",
  steps: [
    { n: "01", title: "Encuentra una empresa", body: "Aprovecha tus contactos, conocimiento del mercado local o tu cartera de clientes actual." },
    { n: "02", title: "Identifica la necesidad", body: "Selecciona el producto o servicio que mejor resuelve la necesidad de la empresa." },
    { n: "03", title: "Presenta AI MARK", body: "Envía tu enlace de referido, comparte la página del producto o realiza la presentación directa." },
    { n: "04", title: "Cierra la venta", body: "El cliente adquiere la solución a través del canal de partner rastreado." },
    { n: "05", title: "AI MARK ejecuta", body: "Configuración, implementación y soporte técnico quedan a cargo del equipo de AI MARK." },
    { n: "06", title: "Desarrolla tu mercado", body: "Multiplica las ventas, expande tu cartera e incorpora nuevos partners a tu red." },
  ],
  networkEyebrow: "Red de partners",
  networkTitle: "Primero ventas directas. Luego crecimiento en red.",
  networkLead: "La red se construye sobre ventas pagadas reales, no registros vacíos. Cinco niveles se reparten el importe efectivamente abonado por el cliente. El 80% es el pool total de partners entre niveles cualificados — no el pago a un solo socio.",
  poolHeadline: "50% por venta directa. Hasta 80% en recompensas totales para socios en la red.",
  poolLead: "L1 recibe el 50% de la base comisionable. Los niveles restantes se reparten el 30%. En conjunto forman un pool de red del 80%. La retención de AI Mark es del 20%.",
  exampleTitle: "En una venta comisionable de $1.000 con una red completa de 5 niveles",
  exampleRows: [
    { label: "Partner directo L1", value: "$500", accent: true },
    { label: "L2", value: "$150" },
    { label: "L3", value: "$70" },
    { label: "L4", value: "$50" },
    { label: "L5", value: "$30" },
    { label: "Pool de partners (agregado)", value: "$800" },
    { label: "Retención de AI Mark", value: "$200" },
  ],
  exampleFoot: "El partner directo recibe $500, no $800. El 80% es el total acumulado entre L1 y L5 cuando todos los niveles están cualificados.",

  renewalExampleTitle: "La misma venta de $1.000 en renovación (desde el 2.º pago)",
  renewalExampleRows: [
    { label: "Partner directo L1", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Pool de partners (agregado)", value: "$250" },
    { label: "Parte retenida de AI Mark", value: "$750" },
  ],
  renewalExampleFoot: "Las renovaciones no repiten la cuadrícula launch bonus de cinco niveles.",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  levels: [
    { n: "L1", title: "Venta directa", body: "El cliente presentado y cerrado personalmente por ti.", rate: "50%" },
    { n: "L2", title: "Primera red", body: "Ventas pagadas de clientes de tus partners de primer nivel.", rate: "15%" },
    { n: "L3", title: "Red extendida", body: "Ventas pagadas un nivel más profundo en la estructura.", rate: "7%" },
    { n: "L4", title: "Profundidad de mercado", body: "Ventas generadas más allá de tus relaciones directas.", rate: "5%" },
    { n: "L5", title: "Máxima profundidad", body: "El nivel más profundo del esquema de afiliados estándar.", rate: "3%" },
  ],
  commissionLabel: "Comisión",
  commissionNote: "L1 50% / L2 15% / L3 7% / L4 5% / L5 3% sobre el importe cobrado. Pool total de red 80%.",
  statusEyebrow: "Estatus de partner",
  statusTitle: "Cuatro etapas de crecimiento con AI MARK.",
  statusLead: "El estatus refleja la actividad comercial y el alcance de las relaciones. Es una posición de negocio por rendimiento, no un rango de pago.",
  statuses: [
    { tag: "START", title: "Partner", body: "Vende soluciones AI MARK, usa tu enlace de referido, accede a recursos comerciales y capta tus primeros clientes." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Vendedor con actividad constante, cartera de clientes en crecimiento y desarrollo activo de red." },
    { tag: "MARKET", title: "Regional Partner", body: "Desarrollo territorial o nacional mediante contactos clave, ventas sistemáticas y liderazgo local." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Agencias, distribuidores y canales B2B corporativos. Country Partner y Strategic Partner operan bajo acuerdo bilateral independiente." },
  ],
  statusNote: "Estatus según rendimiento",
  kitEyebrow: "Infraestructura de partner",
  kitTitle: "Herramientas que el partner tiene disponibles de inmediato.",
  kitLead: "Enlace de referido personal, Partner Dashboard, páginas públicas de productos, recursos de marca y canales de soporte en Telegram, WhatsApp, Messenger y correo.",
  kit: [
    "Enlace de referido personal y Partner ID",
    "Partner Dashboard con seguimiento de ventas, comisiones e historial de pagos",
    "Páginas de productos activas vinculadas a tu enlace de referido",
    "Recursos oficiales de marca y presentaciones comerciales",
    "Atribución completa de leads en formularios, registro de partners y pasarela /pay",
    "Base de conocimiento de productos en tiempo real dentro del Partner Hub",
    "Canales de soporte directo: Telegram, WhatsApp, Messenger y correo electrónico",
  ],
  globalEyebrow: "Expansión global",
  globalTitle: "Elige tu mercado. AI MARK aporta la tecnología.",
  globalLead: "El mismo catálogo probado puede ser implementado por partners en diferentes países e industrias. El tamaño de tu negocio lo define tu alcance comercial.",
  global: [
    "Un núcleo tecnológico unificado: los mismos productos de IA probados en mercados internacionales.",
    "Presencia comercial localizada: adaptas la propuesta, el tono y la relación comercial al mercado local.",
    "Múltiples vías de monetización: ingresos recurrentes de SaaS, retainers mensuales y grandes proyectos digitales.",
    "Escala sin costes de ingeniería propios: AI MARK gestiona la infraestructura técnica y el desarrollo.",
  ],
  faqEyebrow: "FAQ",
  faqTitle: "Preguntas frecuentes de partners.",
  faq: [
    { q: "¿Tengo que comprar un paquete inicial para ser partner?", a: "No. El programa se basa en la venta de productos y servicios reales de AI MARK a empresas, no en comprar posiciones en una red. El registro es gratuito." },
    { q: "¿Debo encargarme de la ejecución técnica?", a: "No. El partner se enfoca en las relaciones y el cierre comercial. AI MARK es responsable de la implementación, entrega y soporte del producto." },
    { q: "¿Puedo construir un equipo de partners?", a: "Sí. El modelo estándar admite una red multinivel vinculada a los ingresos de clientes, con hasta 5 niveles de profundidad." },
    { q: "¿Las suscripciones generan comisiones recurrentes?", a: "Sí. El primer pago usa launch bonus (hasta 31.12.2026) o la cuadrícula inicial estándar desde el 01.01.2027. Desde el 2.º pago, renovaciones solo L1 20% + L2 5%." },
    { q: "¿Cómo acceder al estatus de Regional o Strategic Partner?", a: "El estatus Regional se otorga por volumen comercial acreditado y liderazgo local. Las alianzas Estratégicas y Country Partner se formalizan mediante acuerdo bilateral." },
  ],
  ctaEyebrow: "Inicio",
  ctaTitle: "Tu mercado. Nuestra infraestructura de IA.",
  ctaLead: "Súmate como partner, elige las industrias que mejor dominas y comienza con las empresas a las que tienes acceso directo hoy mismo.",
  ctaButton: "Convertirme en Partner AI MARK",
};
