import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyFr: PartnerPageCopy = {
  metaTitle: "Réseau de Partenaires AI MARK — Développez Votre Marché",
  metaDescription: "Vendez des produits d'IA et des solutions digitales avec AI MARK. Établissez des relations clients, ouvrez de nouveaux marchés et grandissez au sein d'un réseau structuré.",
  eyebrow: "Réseau de Partenaires AI MARK",
  title: "Bâtissez le marché de l'IA dans votre pays.",
  lead: "Vendez de véritables produits d'IA et solutions numériques aux entreprises de votre région. AI MARK fournit la technologie, la livraison des produits et l'infrastructure partenaires. Vous développez les relations et les ventes.",
  note: "50 % pour une vente directe · Jusqu'à 80 % de récompenses totales sur le réseau · Inscription gratuite",
  primary: "Devenir Partenaire",
  secondary: "Comment ça fonctionne",
  marketEyebrow: "Le marché",
  marketTitle: "Un seul portefeuille. Un vaste marché intersectoriel.",
  marketLead: "L'opportunité ne s'arrête pas à une niche. Partout, les entreprises ont besoin d'opérer, d'attirer des clients, de communiquer, de maintenir leur présence en ligne et d'automatiser leurs processus.",
  market: [
    { title: "Opérer", body: "Communication quotidienne, gestion des connaissances, coordination et demandes clients créent une demande continue." },
    { title: "Commercialiser", body: "Chaque entreprise a besoin de visibilité, de contenu, de campagnes régulières et de systèmes de croissance reproductibles." },
    { title: "Construire", body: "Les entreprises en expansion requièrent sites web, portails, applications, intégrations et systèmes sur mesure." },
    { title: "Automatiser", body: "Face à la complexité des flux, la demande s'accélère pour l'IA, l'automatisation et la réduction des coûts manuels." },
  ],
  marketCore: "Votre marché ne se limite pas à un seul produit. C'est chaque entreprise que vous pouvez approcher.",
  productEyebrow: "Portefeuille de produits",
  productTitle: "Quatre façons de créer une valeur concrète pour le client.",
  productLead: "Un partenaire associe la problématique spécifique de l'entreprise à la bonne solution AI MARK, sans chercher à vendre un outil unique à une niche étroite.",
  products: [
    { name: "AI Marketing Employee", type: "RÉCURRENT / PRODUIT IA", body: "Marketing natif IA : recherche, stratégie, rédaction, création visuelle, validation humaine, publication et optimisation continue.", revenue: "Revenu par abonnement", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "RÉCURRENT / PRODUIT IA", body: "Boîte de réception ventes et support connectée à la base de connaissances de l'entreprise, qualifie les leads et relaie aux équipes.", revenue: "Revenu par abonnement", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "RÉCURRENT / PRODUIT IA", body: "Agent commercial IA pour échanger avec le client, explorer le catalogue, appliquer les règles tarifaires et générer des propositions.", revenue: "Revenu par abonnement", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROJET / SERVICE B2B", body: "Sites web, portails, plateformes, intégrations, automatisation et systèmes IA sur mesure pour les entreprises aux besoins étendus.", revenue: "Revenu par projet", variant: "saas" },
  ],
  productCta: "Découvrir le produit",
  productionCta: "Digital Production",
  howEyebrow: "Fonctionnement",
  modelTitle: "Vous vendez. AI MARK déploie et assure la livraison.",
  modelLead: "Le partenaire est l'interface commerciale de terrain. AI MARK garantit le produit convenu, l'infrastructure technique et l'exécution opérationnelle.",
  steps: [
    { n: "01", title: "Identifier une entreprise", body: "Exploitez votre réseau relationnel, vos connaissances locales ou votre portefeuille existant." },
    { n: "02", title: "Cibler le besoin", body: "Sélectionnez le produit ou service répondant précisément à la problématique client." },
    { n: "03", title: "Présenter AI MARK", body: "Partagez votre lien de parrainage, la page du produit ou initiez une mise en relation directe." },
    { n: "04", title: "Conclure la vente", body: "Le client souscrit et règle sa commande via le canal partenaire tracké." },
    { n: "05", title: "AI MARK exécute", body: "Configuration, mise en production et support technique sont intégralement gérés par AI MARK." },
    { n: "06", title: "Étendre votre marché", body: "Renouvelez les signatures, fidélisez vos comptes et intégrez de nouveaux partenaires dans votre réseau." },
  ],
  networkEyebrow: "Réseau de partenaires",
  networkTitle: "Ventes directes d'abord. Ventes de réseau ensuite.",
  networkLead: "Le réseau repose sur les paiements effectifs des clients, et non sur des inscriptions sans activité. Cinq niveaux se partagent le montant réellement versé par le client. 80 % représente le pool global de partenaires sur les niveaux qualifiés — non un paiement à un seul intermédiaire.",
  poolHeadline: "50 % pour une vente directe. Jusqu'à 80 % de récompenses totales sur le réseau.",
  poolLead: "Le niveau 1 perçoit 50 % de la base commissionnable. Les niveaux suivants se partagent 30 %. Ensemble, ils constituent un pool de 80 %. La part conservée par AI Mark est de 20 %.",
  exampleTitle: "Sur une vente commissionnable de 1 000 $ avec un réseau complet à 5 niveaux",
  exampleRows: [
    { label: "Partenaire direct L1", value: "500 $", accent: true },
    { label: "L2", value: "150 $" },
    { label: "L3", value: "70 $" },
    { label: "L4", value: "50 $" },
    { label: "L5", value: "30 $" },
    { label: "Pool de partenaires (agrégé)", value: "800 $" },
    { label: "Part conservée par AI Mark", value: "200 $" },
  ],
  exampleFoot: "Le partenaire direct reçoit 500 $, et non 800 $. 80 % est le montant global cumulé de L1 à L5 lorsque tous les niveaux sont qualifiés.",

  renewalExampleTitle: "Même vente à 1 000 $ à partir du mois 4 (renouvellement)",
  renewalExampleRows: [
    { label: "Partenaire direct L1", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Pool partenaires (agrégé)", value: "$250" },
    { label: "Part retenue AI Mark", value: "$750" },
  ],
  renewalExampleFoot: "Les renouvellements ne répètent pas la grille launch bonus à cinq niveaux.",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  levels: [
    { n: "L1", title: "Vente directe", body: "Le client que vous présentez et concluez personnellement.", rate: "50 %" },
    { n: "L2", title: "Premier réseau", body: "Ventes réglées par les clients de vos partenaires de premier niveau.", rate: "15 %" },
    { n: "L3", title: "Réseau étendu", body: "Ventes validées un échelon plus bas dans votre organisation.", rate: "7 %" },
    { n: "L4", title: "Profondeur de marché", body: "Ventes réalisées au-delà de vos relations directes.", rate: "5 %" },
    { n: "L5", title: "Profondeur maximale", body: "Le dernier niveau du plan de commissionnement standard.", rate: "3 %" },
  ],
  commissionLabel: "Commission",
  commissionNote: "L1 50 % / L2 15 % / L3 7 % / L4 5 % / L5 3 % sur le montant encaissé. Pool total du réseau 80 %.",
  statusEyebrow: "Statut de partenaire",
  statusTitle: "Quatre paliers de progression avec AI MARK.",
  statusLead: "Le statut traduit le volume d'activité commerciale et l'engagement mutuel. C'est une qualification de performance, non un grade payant.",
  statuses: [
    { tag: "START", title: "Partner", body: "Distribuez les offres AI MARK, diffusez votre lien affilié, accédez aux supports et signez vos premiers clients." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Vendeur régulier disposant d'un portefeuille de clients en expansion et d'un réseau naissant." },
    { tag: "MARKET", title: "Regional Partner", body: "Développement d'un territoire ou d'un pays par des relations institutionnelles, ventes suivies et animation locale." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Agences, distributeurs et grands canaux B2B. Country Partner et Strategic Partner font l'objet d'accords bilatéraux dédiés." },
  ],
  statusNote: "Statut selon performance",
  kitEyebrow: "Infrastructure partenaire",
  kitTitle: "Ce dont dispose le partenaire dès son inscription.",
  kitLead: "Lien de parrainage personnel, Partner Dashboard, pages produits en ligne, kit de marque et support réactif sur Telegram, WhatsApp, Messenger et e-mail.",
  kit: [
    "Lien de recommandation personnel et Partner ID",
    "Partner Dashboard avec suivi en direct des ventes, commissions et historique des retraits",
    "Pages publiques de produits affiliées à votre identifiant",
    "Fichiers officiels de marque et argumentaires de vente",
    "Attribution complète des leads sur formulaires, inscription partenaire et passerelle /pay",
    "Spécifications détaillées et base de faits produits au sein du Partner Hub",
    "Support dédié : Telegram, WhatsApp, Messenger et e-mail",
  ],
  globalEyebrow: "Expansion internationale",
  globalTitle: "Choisissez le marché. AI MARK assure la technologie.",
  globalLead: "Le même catalogue de solutions peut être déployé par différents partenaires dans des pays et des secteurs variés. La seule limite est votre rayonnement commercial.",
  global: [
    "Cœur technologique unifié : les mêmes outils d'IA éprouvés déployés auprès de clients internationaux.",
    "Présence commerciale localisée : vous adaptez le discours, la culture et l'approche au contexte local.",
    "Multiples flux de revenus : récurrence SaaS, contrats d'accompagnement mensuels et grands projets de production.",
    "Croissance sans masse salariale technique : AI MARK prend en charge l'infrastructure et la R&D.",
  ],
  faqEyebrow: "FAQ",
  faqTitle: "Questions fréquentes des partenaires.",
  faq: [
    { q: "Faut-il acheter un pack de démarrage pour devenir partenaire ?", a: "Non. Le programme récompense la vente de produits et services réels aux entreprises, et non l'achat de positions. L'accès est gratuit." },
    { q: "Dois-je gérer la livraison technique du projet ?", a: "Non. Le partenaire gère la relation et le closing. AI MARK assure l'implémentation, la livraison et le suivi technique." },
    { q: "Puis-je constituer une équipe de partenaires ?", a: "Oui. Le modèle standard permet d'animer une équipe d'affiliés jusqu'à 5 niveaux de profondeur, adossée au chiffre d'affaires réel." },
    { q: "Les abonnements génèrent-ils des commissions récurrentes ?", a: "Oui. Mois 1–3 : launch bonus (jusqu’au 31.12.2026) ou grille initiale standard dès le 01.01.2027. À partir du mois 4 : L1 20 % + L2 5 % seulement." },
    { q: "Comment obtenir le statut de Regional ou Strategic Partner ?", a: "Le statut régional est attribué selon le volume d'affaires et la présence locale. Les partenariats stratégiques s'établissent sur contrat sur mesure." },
  ],
  ctaEyebrow: "Démarrage",
  ctaTitle: "Votre marché. Notre infrastructure d'IA.",
  ctaLead: "Rejoignez le réseau AI MARK, choisissez vos secteurs de prédilection et commencez avec les entreprises de votre écosystème dès aujourd'hui.",
  ctaButton: "Devenir Partenaire AI MARK",
};
