import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyId: PartnerPageCopy = {
  metaTitle: "Jaringan Mitra AI MARK — Bangun Pasar Anda",
  metaDescription: "Jual produk AI dan solusi digital bersama AI MARK. Bangun relasi pelanggan, kembangkan pasar baru, dan bertumbuh melalui jaringan kemitraan terstruktur.",
  eyebrow: "Jaringan Mitra AI MARK",
  title: "Bangun pasar AI di negara Anda.",
  lead: "Jual produk AI nyata dan solusi digital kepada bisnis di wilayah Anda. AI MARK menyediakan teknologi, pengiriman produk, dan infrastruktur mitra. Anda membangun relasi dan penjualan.",
  note: "50% untuk penjualan langsung · Hingga 80% total reward mitra di seluruh jaringan · Gratis bergabung",
  primary: "Menjadi Mitra",
  secondary: "Lihat cara kerjanya",
  marketEyebrow: "Peluang Pasar",
  marketTitle: "Satu portofolio. Pasar luas lintas industri.",
  marketLead: "Peluang ini tidak terbatas pada satu ceruk saja. Bisnis di mana pun perlu beroperasi, menarik pelanggan, berkomunikasi, menjaga kehadiran digital, dan mengotomatiskan rutinitas.",
  market: [
    { title: "Operasional", body: "Komunikasi rutin, manajemen pengetahuan, koordinasi, dan permintaan pelanggan menciptakan permintaan operasional yang konsisten." },
    { title: "Pemasaran", body: "Setiap bisnis membutuhkan visibilitas, konten berkualitas, kampanye terarah, dialog pelanggan, dan sistem pertumbuhan yang teruji." },
    { title: "Pengembangan", body: "Perusahaan yang berkembang membutuhkan situs web, portal klien, aplikasi, integrasi, dan sistem digital khusus." },
    { title: "Otomasi", body: "Seiring makin kompleksnya alur kerja, permintaan akan AI, otomatisasi, dan sistem pengurang beban manual meningkat pesat." },
  ],
  marketCore: "Pasar Anda bukan satu produk saja. Pasar Anda adalah setiap bisnis yang dapat Anda jangkau.",
  productEyebrow: "Portofolio Produk",
  productTitle: "Empat cara menciptakan nilai nyata bagi pelanggan.",
  productLead: "Mitra dapat mencocokkan masalah bisnis pelanggan dengan solusi AI MARK yang tepat, alih-alih memaksakan satu alat ke target pasar yang sempit.",
  products: [
    { name: "AI Marketing Employee", type: "BERLANGGANAN / PRODUK AI", body: "Pemasaran AI-native: riset, strategi, konten, produksi kreatif, persetujuan, publikasi, dan optimasi berkelanjutan.", revenue: "Pendapatan langganan", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "BERLANGGANAN / PRODUK AI", body: "Kotak masuk penjualan dan dukungan berbasis basis pengetahuan bisnis, mengkualifikasi prospek, dan mengalihkan ke manusia bila perlu.", revenue: "Pendapatan langganan", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "BERLANGGANAN / PRODUK AI", body: "Agen penjualan AI untuk dialog konsultatif, pemilihan katalog, aturan harga, spesifikasi teknis, dan proposal komersial.", revenue: "Pendapatan langganan", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROYEK / LAYANAN B2B", body: "Situs web, portal, platform aplikasi, integrasi, dan sistem AI khusus untuk bisnis dengan kebutuhan infrastruktur berskala besar.", revenue: "Pendapatan proyek", variant: "saas" },
  ],
  productCta: "Pelajari produk",
  productionCta: "Produksi Digital",
  howEyebrow: "Cara Kerja",
  modelTitle: "Anda menjual. AI MARK membangun dan mengeksekusi.",
  modelLead: "Mitra adalah antarmuka pasar. AI MARK bertanggung jawab penuh atas produk yang disepakati, teknologi, dan keandalan operasional.",
  steps: [
    { n: "01", title: "Temukan bisnis", body: "Manfaatkan jaringan relasi, pemahaman pasar lokal, atau basis pelanggan yang sudah ada." },
    { n: "02", title: "Petakan kebutuhan", body: "Pilih produk atau layanan yang secara tepat mengatasi hambatan bisnis klien." },
    { n: "03", title: "Perkenalkan AI MARK", body: "Kirim tautan rujukan personal, halaman produk langsung, atau jadwalkan pertemuan." },
    { n: "04", title: "Tutup penjualan", body: "Pelanggan memesan dan membayar melalui kanal mitra yang terlacak secara transparan." },
    { n: "05", title: "AI MARK mengeksekusi", body: "Pengaturan sistem, implementasi, dan dukungan teknis ditangani sepenuhnya oleh tim AI MARK." },
    { n: "06", title: "Kembangkan pasar Anda", body: "Perbanyak transaksi, perbesar portofolio klien, dan rekrut mitra baru ke dalam jaringan Anda." },
  ],
  networkEyebrow: "Jaringan Kemitraan",
  networkTitle: "Penjualan langsung terlebih dahulu. Penjualan jaringan berikutnya.",
  networkLead: "Jaringan kemitraan dibangun berdasarkan pembayaran pelanggan nyata, bukan pendaftaran kosong. Lima tingkatan berbagi nilai yang dibayar pelanggan. 80% adalah total pool mitra di seluruh level yang memenuhi syarat — bukan pembayaran kepada satu mitra saja.",
  poolHeadline: "50% untuk penjualan langsung. Hingga 80% total pool mitra di seluruh jaringan.",
  poolLead: "Level 1 (L1) memperoleh 50% dari basis komisi. Level lainnya berbagi 30%. Bersama-sama membentuk pool jaringan 80%. Bagian yang ditahan AI Mark adalah 20%.",
  exampleTitle: "Pada penjualan bernilai komisi $1.000 dengan jaringan 5 level lengkap",
  exampleRows: [
    { label: "Mitra langsung L1", value: "$500", accent: true },
    { label: "L2", value: "$150" },
    { label: "L3", value: "$70" },
    { label: "L4", value: "$50" },
    { label: "L5", value: "$30" },
    { label: "Pool mitra (agregat)", value: "$800" },
    { label: "Bagian ditahan AI Mark", value: "$200" },
  ],
  exampleFoot: "Mitra langsung menerima $500, bukan $800. 80% adalah total akumulasi dari L1 hingga L5 saat semua level memenuhi kualifikasi.",

  renewalExampleTitle: "Penjualan $1.000 yang sama dari bulan ke-4 (perpanjangan)",
  renewalExampleRows: [
    { label: "Mitra langsung L1", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Pool mitra (agregat)", value: "$250" },
    { label: "Bagian AI Mark yang ditahan", value: "$750" },
  ],
  renewalExampleFoot: "Perpanjangan tidak mengulang kisi launch bonus lima tingkat penuh.",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  levels: [
    { n: "L1", title: "Penjualan langsung", body: "Pelanggan yang Anda perkenalkan dan transaksikan secara langsung.", rate: "50%" },
    { n: "L2", title: "Jaringan tingkat pertama", body: "Penjualan dari pelanggan mitra tingkat pertama yang Anda sponsori.", rate: "15%" },
    { n: "L3", title: "Jaringan yang diperluas", body: "Penjualan terbayar satu tingkat lebih dalam di organisasi Anda.", rate: "7%" },
    { n: "L4", title: "Kedalaman pasar", body: "Penjualan yang berkembang melampaui relasi langsung Anda.", rate: "5%" },
    { n: "L5", title: "Kedalaman maksimal", body: "Tingkat terdalam dari struktur komisi afiliasi standar.", rate: "3%" },
  ],
  commissionLabel: "Komisi",
  commissionNote: "L1 50% / L2 15% / L3 7% / L4 5% / L5 3% dari jumlah yang diterima. Total pool jaringan 80%.",
  statusEyebrow: "Status Kemitraan",
  statusTitle: "Empat jenjang perkembangan bersama AI MARK.",
  statusLead: "Status mencerminkan volume aktivitas komersial dan kedalaman kolaborasi. Ini adalah status bisnis berdasarkan performa, bukan peringkat yang dibeli.",
  statuses: [
    { tag: "START", title: "Partner", body: "Jual produk AI MARK, gunakan tautan rujukan, akses materi resmi, dan raih pelanggan pertama Anda." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Penjual aktif konsisten dengan portofolio pelanggan yang berkembang dan pembentukan jaringan awal." },
    { tag: "MARKET", title: "Regional Partner", body: "Memimpin ekspansi regional atau nasional melalui relasi strategis, penjualan terkoordinasi, dan kepemimpinan pasar." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Agensi besar, distributor, dan kanal korporasi B2B. Country Partner dan Strategic Partner diatur melalui perjanjian bilateral terpisah." },
  ],
  statusNote: "Status berdasarkan performa",
  kitEyebrow: "Infrastruktur Mitra",
  kitTitle: "Alat yang langsung dapat digunakan mitra.",
  kitLead: "Tautan rujukan personal, Partner Dashboard, halaman produk publik, materi merek resmi, dan dukungan langsung via Telegram, WhatsApp, Messenger, serta email.",
  kit: [
    "Tautan rujukan personal dan kode Partner ID unik",
    "Partner Dashboard dengan pemantauan penjualan, komisi, dan riwayat penarikan secara real-time",
    "Halaman produk publik yang terhubung langsung dengan kode pelacakan Anda",
    "Aset merek resmi, dokumen presentasi bisnis, dan panduan penjualan",
    "Pelacakan prospek akurat di formulir situs web, pendaftaran mitra, dan halaman pembayaran /pay",
    "Basis data spesifikasi dan fakta produk resmi di dalam Partner Hub",
    "Kanal dukungan responsif: Telegram, WhatsApp, Messenger, dan email",
  ],
  globalEyebrow: "Ekspansi Global",
  globalTitle: "Pilih pasarnya. AI MARK menyediakan teknologinya.",
  globalLead: "Koleksi produk yang teruji ini dapat ditawarkan oleh berbagai mitra di berbagai negara dan industri. Skala bisnis Anda hanya dibatasi oleh daya jangkau Anda sendiri.",
  global: [
    "Inti teknologi terpadu: Produk AI kelas dunia yang sama diterapkan untuk klien internasional.",
    "Pendekatan komersial lokal: Anda menyesuaikan gaya komunikasi dan negosiasi sesuai budaya pasar setempat.",
    "Banyak jalur monetisasi: Langganan SaaS rutin, paket retainer bulanan, dan proyek digital bernilai tinggi.",
    "Ekspansi tanpa biaya tim teknis: AI MARK menangani seluruh pengembangan perangkat lunak dan infrastruktur.",
  ],
  faqEyebrow: "FAQ",
  faqTitle: "Pertanyaan umum seputar kemitraan.",
  faq: [
    { q: "Apakah saya harus membeli paket pemula untuk menjadi mitra?", a: "Tidak. Program ini murni berfokus pada penjualan produk dan layanan AI MARK kepada bisnis nyata, bukan membeli posisi dalam jaringan. Pendaftaran 100% gratis." },
    { q: "Apakah saya harus menangani implementasi teknis sendiri?", a: "Tidak. Mitra fokus pada hubungan dan penutupan penjualan. AI MARK bertanggung jawab atas penerapan, pengiriman, dan pemeliharaan teknis produk." },
    { q: "Bisakah saya membangun tim dan jaringan mitra sendiri?", a: "Bisa. Model standar mendukung struktur afiliasi multi-tier hingga 5 tingkat kedalaman yang terikat langsung pada pendapatan pelanggan riil." },
    { q: "Apakah produk langganan memberikan komisi berkelanjutan?", a: "Ya. Pembayaran pertama memakai launch bonus (hingga 31.12.2026) atau kisi awal standar dari 01.01.2027. Dari pembayaran ke-2, perpanjangan hanya L1 20% + L2 5%." },
    { q: "Bagaimana cara menjadi Regional atau Strategic Partner?", a: "Status Regional diberikan berdasarkan volume transaksi terverifikasi dan posisi pasar. Kemitraan strategis dan Country Partner disepakati lewat perjanjian bilateral khusus." },
  ],
  ctaEyebrow: "Mulai Sekarang",
  ctaTitle: "Pasar Anda. Infrastruktur AI kami.",
  ctaLead: "Bergabunglah sebagai mitra AI MARK, tentukan sektor bisnis yang Anda kuasai, dan mulailah dengan bisnis yang dapat Anda jangkau hari ini.",
  ctaButton: "Menjadi Mitra AI MARK",
};
