import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyPt: PartnerPageCopy = {
  metaTitle: "Rede de Parceiros AI MARK — Construa o seu Mercado",
  metaDescription: "Venda produtos de IA e soluções digitais com a AI MARK. Desenvolva relações comerciais, expanda novos mercados e cresça através de uma rede estruturada de parceiros.",
  eyebrow: "Rede de Parceiros AI MARK",
  title: "Construa o mercado de IA no seu país.",
  lead: "Venda produtos reais de IA e soluções digitais para empresas da sua região. A AI MARK fornece a tecnologia, a entrega de produto e a infraestrutura de parceiros. Você constrói os relacionamentos e as vendas.",
  note: "50% por venda direta · Até 80% em recompensas totais para parceiros na rede · Inscrição gratuita",
  primary: "Tornar-se Parceiro",
  secondary: "Como funciona",
  marketEyebrow: "O mercado",
  marketTitle: "Um portfólio. Um vasto mercado multissetorial.",
  marketLead: "A oportunidade não está limitada a um nicho. Empresas em todos os setores precisam operar, captar clientes, comunicar, manter presença digital e automatizar rotinas.",
  market: [
    { title: "Operar", body: "Comunicação diária, gestão de conhecimento, coordenação e solicitações de clientes geram procura contínua." },
    { title: "Divulgar", body: "Todas as empresas necessitam de visibilidade, conteúdo, campanhas, contacto frequente com clientes e processos replicáveis de crescimento." },
    { title: "Construir", body: "Empresas em expansão exigem websites, portais, aplicações, integrações e sistemas digitais sob medida." },
    { title: "Automatizar", body: "Com o aumento da complexidade, cresce a procura por IA, automações e soluções que eliminam trabalho manual." },
  ],
  marketCore: "O seu mercado não é apenas um produto. É qualquer empresa que você possa alcançar.",
  productEyebrow: "Portfólio de produtos",
  productTitle: "Quatro formas de gerar valor real para o cliente.",
  productLead: "O parceiro identifica a dor concreta de uma empresa e direciona a solução certa da AI MARK, em vez de insistir num produto único para um nicho estreito.",
  products: [
    { name: "AI Marketing Employee", type: "RECORRENTE / PRODUTO DE IA", body: "Marketing nativo com IA: pesquisa, estratégia, redação, produção criativa, aprovação, publicação e otimização.", revenue: "Receita por subscrição", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "RECORRENTE / PRODUTO DE IA", body: "Caixa de entrada para vendas e suporte com base de conhecimento empresarial, qualificação de leads e transição fluida para humanos.", revenue: "Receita por subscrição", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "RECORRENTE / PRODUTO DE IA", body: "Agente comercial de IA para atendimento, consulta de catálogo, cálculo por regras de preço, propostas e orçamentos.", revenue: "Receita por subscrição", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROJETO / SERVIÇO B2B", body: "Websites, portais, aplicações, integrações, automação e sistemas sob medida de IA para empresas com necessidades robustas.", revenue: "Receita por projeto", variant: "saas" },
  ],
  productCta: "Explorar produto",
  productionCta: "Digital Production",
  howEyebrow: "Como funciona",
  modelTitle: "Você vende. A AI MARK entrega e sustenta.",
  modelLead: "O parceiro é o elo comercial com o mercado. A AI MARK responsabiliza-se pela tecnologia, engenharia e entrega contratada.",
  steps: [
    { n: "01", title: "Encontre uma empresa", body: "Utilize a sua rede de contactos, conhecimento local ou carteira ativa de clientes." },
    { n: "02", title: "Identifique a necessidade", body: "Escolha o produto ou serviço que resolve o problema concreto da empresa." },
    { n: "03", title: "Apresente a AI MARK", body: "Envie a sua ligação de referência, página de produto ou agende uma reunião direta." },
    { n: "04", title: "Feche a venda", body: "O cliente contrata a solução através do canal monitorizado do parceiro." },
    { n: "05", title: "A AI MARK executa", body: "Configuração, implementação e suporte técnico ficam a cargo da equipa AI MARK." },
    { n: "06", title: "Expanda o seu mercado", body: "Escale as vendas, aumente a retenção e adicione parceiros à sua organização." },
  ],
  networkEyebrow: "Rede de parceiros",
  networkTitle: "Vendas diretas em primeiro lugar. Vendas em rede a seguir.",
  networkLead: "A rede baseia-se em vendas reais pagas, e não em cadastros sem atividade. Cinco níveis partilham o montante efetivamente liquidado pelo cliente. 80% é o pool global de parceiros nos níveis qualificados — não um pagamento a um parceiro isolado.",
  poolHeadline: "50% por venda direta. Até 80% em recompensas totais para parceiros na rede.",
  poolLead: "O Nível 1 recebe 50% do valor comissionável. Os restantes níveis dividem 30%. Juntos perfazem um pool de rede de 80%. A parte retida da AI Mark é de 20%.",
  exampleTitle: "Numa venda comissionável de $1.000 com rede completa de 5 níveis",
  exampleRows: [
    { label: "Parceiro direto L1", value: "$500", accent: true },
    { label: "L2", value: "$150" },
    { label: "L3", value: "$70" },
    { label: "L4", value: "$50" },
    { label: "L5", value: "$30" },
    { label: "Pool de parceiros (agregado)", value: "$800" },
    { label: "Retenção da AI Mark", value: "$200" },
  ],
  exampleFoot: "O parceiro direto recebe $500, e não $800. 80% é o montante acumulado entre L1 e L5 quando todos os níveis estão qualificados.",

  renewalExampleTitle: "Same $1,000 sale from month 4 onward (renewal)",
  renewalExampleRows: [
    { label: "L1 direct partner", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Partner pool (aggregate)", value: "$250" },
    { label: "AI Mark retained share", value: "$750" },
  ],
  renewalExampleFoot: "Renewals do not repeat the full five-level launch bonus grid.",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  levels: [
    { n: "L1", title: "Venda direta", body: "O cliente apresentado e convertido diretamente por si.", rate: "50%" },
    { n: "L2", title: "Primeira rede", body: "Vendas pagas de clientes dos seus parceiros de primeiro nível.", rate: "15%" },
    { n: "L3", title: "Rede alargada", body: "Vendas pagas mais um nível abaixo na sua estrutura.", rate: "7%" },
    { n: "L4", title: "Profundidade de mercado", body: "Vendas geradas para lá das suas relações diretas.", rate: "5%" },
    { n: "L5", title: "Profundidade máxima", body: "O escalão final do modelo de afiliados padrão.", rate: "3%" },
  ],
  commissionLabel: "Comissão",
  commissionNote: "L1 50% / L2 15% / L3 7% / L4 5% / L5 3% sobre o valor recebido. Pool agregado de rede 80%.",
  statusEyebrow: "Estatuto do parceiro",
  statusTitle: "Quatro patamares de evolução com a AI MARK.",
  statusLead: "O estatuto reflete a atividade comercial e a maturidade das relações. É um patamar de negócio por mérito, não uma patente paga.",
  statuses: [
    { tag: "START", title: "Partner", body: "Venda soluções AI MARK, utilize o seu link de afiliado, aceda a materiais de apoio e ative os primeiros clientes." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Vendedor com ritmo constante, portfólio crescente de clientes e rede inicial em desenvolvimento." },
    { tag: "MARKET", title: "Regional Partner", body: "Desenvolvimento de uma região ou país com contactos estruturados, vendas recorrentes e coordenação local." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Agências, integradores e grandes canais B2B. Country Partner e Strategic Partner dependem de acordo bilateral próprio." },
  ],
  statusNote: "Estatuto por desempenho",
  kitEyebrow: "Infraestrutura de parceiro",
  kitTitle: "O que o parceiro tem disponível de imediato.",
  kitLead: "Link de referência pessoal, Partner Dashboard, páginas públicas de produtos, recursos de marca e canais de apoio no Telegram, WhatsApp, Messenger e email.",
  kit: [
    "Link de referência pessoal e Partner ID",
    "Partner Dashboard com registo de vendas, comissões e histórico de levantamentos",
    "Páginas de produtos ativas associadas ao seu código de parceiro",
    "Materiais oficiais de marca e apresentações comerciais",
    "Atribuição de leads em formulários de contacto, registo de parceiros e /pay",
    "Base de factos e especificações de produtos dentro do Partner Hub",
    "Suporte multicanal: Telegram, WhatsApp, Messenger e correio eletrónico",
  ],
  globalEyebrow: "Expansão global",
  globalTitle: "Escolha o mercado. A AI MARK assegura a tecnologia.",
  globalLead: "O mesmo conjunto de produtos consolidados pode ser comercializado por diferentes parceiros em vários países e setores. O limite é apenas a sua capacidade de alcance.",
  global: [
    "Núcleo de produto unificado: as mesmas soluções de ponta em IA utilizadas globalmente.",
    "Presença comercial adaptada: o parceiro alinha abordagem, cultura e negociação ao mercado local.",
    "Diversas fontes de receita: SaaS recorrente, avenças mensais e projetos digitais de alto valor.",
    "Escala sem custos fixos de tecnologia: a AI MARK assegura todo o desenvolvimento e infraestrutura.",
  ],
  faqEyebrow: "FAQ",
  faqTitle: "Perguntas frequentes dos parceiros.",
  faq: [
    { q: "É obrigatório adquirir um pacote inicial para ser parceiro?", a: "Não. O programa orienta-se à venda real de produtos e serviços AI MARK a empresas, não à compra de posições. A adesão é gratuita." },
    { q: "Preciso de assumir a execução técnica do projeto?", a: "Não. O parceiro constrói o relacionamento e fecha o negócio. A AI MARK responsabiliza-se pela implementação, entrega e estabilidade técnica." },
    { q: "Posso criar e gerir uma equipa de parceiros?", a: "Sim. O modelo padrão comporta uma estrutura de afiliados até 5 níveis de profundidade, baseada no faturamento real de clientes." },
    { q: "Os produtos por subscrição geram comissões recorrentes?", a: "Sim. Cada renovação paga qualificada segue a tabela padrão: L1 50%, L2 15%, L3 7%, L4 5%, L5 3%, num pool agregado de 80%. O período inicial de 90 dias não altera estas taxas." },
    { q: "Como aceder ao estatuto de Regional ou Strategic Partner?", a: "O estatuto Regional baseia-se em volume de vendas e liderança territorial. Alianças Estratégicas e Country Partner são celebradas sob contrato específico." },
  ],
  ctaEyebrow: "Início",
  ctaTitle: "O seu mercado. A nossa infraestrutura de IA.",
  ctaLead: "Registe-se como parceiro, selecione os setores em que possui maior facilidade de acesso e comece a fechar com empresas reais hoje mesmo.",
  ctaButton: "Tornar-se Parceiro AI MARK",
};
