import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyTr: PartnerPageCopy = {
  metaTitle: "AI MARK Ortaklık Ağı — Pazarınızı Oluşturun",
  metaDescription: "AI MARK ile yapay zekâ ürünleri ve dijital çözümler satın. Müşteri ilişkileri geliştirin, yeni pazarlar açın ve yapılandırılmış ortaklık ağıyla büyüyün.",
  eyebrow: "AI MARK Ortaklık Ağı",
  title: "Ülkenizde yapay zekâ pazarını inşa edin.",
  lead: "Bölgenizdeki işletmelere gerçek yapay zekâ ürünleri ve dijital çözümler sunun. AI MARK teknolojiyi, ürün teslimatını ve ortaklık altyapısını sağlar. Siz ilişkileri kurar ve satışları tamamlarsınız.",
  note: "Doğrudan satışta %50 · Ağ genelinde %80'e varan ortak ödül havuzu · Katılım ücretsizdir",
  primary: "Ortak Olun",
  secondary: "Nasıl çalıştığını görün",
  marketEyebrow: "Pazar Fırsatı",
  marketTitle: "Tek bir portföy. Sektörler arası geniş bir pazar.",
  marketLead: "Fırsat tek bir nişle sınırlı değildir. Her sektördeki işletmelerin operasyon yürütmeye, müşteri kazanmaya, iletişime, dijital varlığını korumaya ve rutinleri otomatikleştirmeye ihtiyacı vardır.",
  market: [
    { title: "Operasyon", body: "Rutin iletişim, bilgi yönetimi, koordinasyon ve müşteri talepleri kesintisiz operasyonel talep yaratır." },
    { title: "Pazarlama", body: "Her işletme görünürlüğe, içeriğe, kampanyalara, müşteri diyaloglarına ve tekrarlanabilir bir büyüme sistemine ihtiyaç duyar." },
    { title: "Dijital Üretim", body: "Büyüyen şirketler web sitelerine, portallara, uygulamalara, entegrasyonlara ve özel dijital sistemlere ihtiyaç duyar." },
    { title: "Otomasyon", body: "Süreçler karmaşıklaştıkça yapay zekâya, otomasyona ve manuel iş gücü maliyetlerini azaltan sistemlere olan talep hızla artar." },
  ],
  marketCore: "Pazarınız tek bir ürünle sınırlı değildir. Ulaşabileceğiniz her işletme sizin pazarınızdır.",
  productEyebrow: "Ürün Portföyü",
  productTitle: "Müşteriye değer katmanın dört somut yolu.",
  productLead: "Bir ortak, tek bir aracı dar bir kitleye dayatmak yerine müşterinin iş sorununu doğru AI MARK çözümüyle buluşturur.",
  products: [
    { name: "AI Marketing Employee", type: "DÜZENLİ / YAPAY ZEKÂ ÜRÜNÜ", body: "Yapay zekâ tabanlı pazarlama: araştırma, strateji, metin yazımı, görsel üretim, onay, yayınlama ve sürekli optimizasyon.", revenue: "Abonelik geliri", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "DÜZENLİ / YAPAY ZEKÂ ÜRÜNÜ", body: "İşletmenin bilgi tabanından çalışan, talepleri filtreleyen ve gerektiğinde insan ekibe aktaran satış ve destek gelen kutusu.", revenue: "Abonelik geliri", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "DÜZENLİ / YAPAY ZEKÂ ÜRÜNÜ", body: "Müşteri diyaloğu, katalog seçimi, fiyatlandırma kuralları, şartnameler ve ticari teklifler hazırlayan yapay zekâ satış temsilcisi.", revenue: "Abonelik geliri", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "PROJE / B2B HİZMET", body: "Geniş dijital altyapıya ihtiyaç duyan işletmeler için web siteleri, portallar, uygulamalar, entegrasyonlar ve özel yapay zekâ sistemleri.", revenue: "Proje geliri", variant: "saas" },
  ],
  productCta: "Ürünü incele",
  productionCta: "Dijital Üretim",
  howEyebrow: "Nasıl Çalışır",
  modelTitle: "Siz satarsınız. AI MARK teslim eder ve çalıştırır.",
  modelLead: "Ortak, pazarın arayüzüdür. AI MARK ise kararlaştırılan ürün kalitesinden, teknolojiden ve teslimattan sorumludur.",
  steps: [
    { n: "01", title: "Bir işletme bulun", body: "Kişisel bağlantılarınızı, yerel pazar bilginizi veya mevcut müşteri portföyünüzü kullanın." },
    { n: "02", title: "İhtiyacı belirleyin", body: "İşletmenin sorununu en iyi çözen ürünü veya dijital hizmeti seçin." },
    { n: "03", title: "AI MARK'ı tanıtın", body: "Özel yönlendirme bağlantınızı gönderin, ürün sayfasını paylaşın veya doğrudan tanıştırın." },
    { n: "04", title: "Satışı kapatın", body: "Müşteri izlenen ortaklık kanalı üzerinden sipariş verir ve ödemesini tamamlar." },
    { n: "05", title: "AI MARK teslim eder", body: "Kurulum, entegrasyon ve teknik destek süreçleri tamamen AI MARK ekibi tarafından yürütülür." },
    { n: "06", title: "Pazarınızı büyütün", body: "Satışları tekrarlayın, müşteri tabanınızı genişletin ve ağınıza yeni ortaklar dahil edin." },
  ],
  networkEyebrow: "Ortaklık Ağı",
  networkTitle: "Önce kişisel satışlar. Ardından ağ satışları.",
  networkLead: "Ağ, içi boş kayıtlara değil müşterilerin fiilen yaptığı ödemelere dayanır. Beş seviye müşterinin fiilen ödediği tutarı paylaşır. %80, nitelikli seviyeler arasındaki toplam ortak havuzudur — tek bir ortağa yapılan ödeme değildir.",
  poolHeadline: "Doğrudan satışta %50. Ağ genelinde %80'e varan toplam ortak havuzu.",
  poolLead: "1. Kademe (L1) komisyon matrahının %50'sini alır. Kalan kademeler %30'u paylaşır. Birlikte %80'lik bir ağ havuzu oluştururlar. AI Mark'ın tutulan payı %20'dir.",
  exampleTitle: "Tüm kademeleri nitelikli 1.000 dolarlık bir satış örneğinde",
  exampleRows: [
    { label: "L1 doğrudan ortak", value: "$500", accent: true },
    { label: "L2", value: "$150" },
    { label: "L3", value: "$70" },
    { label: "L4", value: "$50" },
    { label: "L5", value: "$30" },
    { label: "Ortak havuzu (toplam)", value: "$800" },
    { label: "AI Mark tutulan payı", value: "$200" },
  ],
  exampleFoot: "Doğrudan ortak $500 alır, $800 değil. %80, her kademe nitelikli olduğunda L1–L5 genelindeki toplam orandır.",
  levels: [
    { n: "L1", title: "Doğrudan satış", body: "Bizzat tanıştırdığınız ve satışını gerçekleştirdiğiniz müşteri.", rate: "%50" },
    { n: "L2", title: "İlk ağ seviyesi", body: "Birinci kademe ortaklarınızın müşterilerinden gelen ödemeler.", rate: "%15" },
    { n: "L3", title: "Genişletilmiş ağ", body: "Organizasyonunuzda bir kademe daha derindeki ödemeler.", rate: "%7" },
    { n: "L4", title: "Pazar derinliği", body: "Doğrudan ilişkilerinizin ötesinde gerçekleşen satışlar.", rate: "%5" },
    { n: "L5", title: "Maksimum derinlik", body: "Standart ortaklık planının en derin kademesi.", rate: "%3" },
  ],
  commissionLabel: "Komisyon",
  commissionNote: "Tahsil edilen tutar üzerinden L1 %50 / L2 %15 / L3 %7 / L4 %5 / L5 %3. Toplam ağ havuzu %80.",
  statusEyebrow: "Ortaklık Statüsü",
  statusTitle: "AI MARK ile büyümenin dört aşaması.",
  statusLead: "Statü ticari hacmi ve iş birliği derinliğini yansıtır. Başarıya dayalı bir statüdür, parayla satın alınamaz.",
  statuses: [
    { tag: "START", title: "Partner", body: "AI MARK ürünlerini satın, yönlendirme bağlantınızı ve materyalleri kullanarak ilk müşterilerinizi edinin." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Sürekli satış yapan, büyüyen bir müşteri portföyüne ve gelişen bir ortak ağına sahip ortak." },
    { tag: "MARKET", title: "Regional Partner", body: "Yerel ilişkiler, satış faaliyetleri ve koordineli büyüme yoluyla bir bölgeyi veya ülkeyi geliştiren lider." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Ajanslar, distribütörler ve büyük B2B kanalları. Ülke Temsilciliği ve Stratejik Ortaklık ayrı sözleşmelere tabidir." },
  ],
  statusNote: "Performansa dayalı statü",
  kitEyebrow: "Ortak Altyapısı",
  kitTitle: "Ortağın hemen kullanabileceği araçlar.",
  kitLead: "Kişisel yönlendirme bağlantısı, Partner Dashboard, yayındaki ürün sayfaları, marka materyalleri ve Telegram, WhatsApp, Messenger ve e-posta destek hatları.",
  kit: [
    "Kişisel yönlendirme bağlantısı ve Partner ID",
    "Satışlarınızı, komisyonlarınızı ve ödeme geçmişinizi izleyen Partner Dashboard",
    "Ortaklık kodunuza bağlı çalışan ürün açılış sayfaları",
    "Resmî marka dosyaları ve ticari sunum materyalleri",
    "İletişim formlarında, ortak kaydında ve /pay sayfasında uçtan uca müşteri takibi",
    "Partner Hub içinde güncel ürün bilgileri ve teknik özellikler",
    "Hızlı destek: Telegram, WhatsApp, Messenger ve e-posta",
  ],
  globalEyebrow: "Küresel Genişleme",
  globalTitle: "Pazarı siz seçin. AI MARK teknolojiyi sağlasın.",
  globalLead: "Aynı kanıtlanmış ürün portföyü farklı ülkelerdeki ve sektörlerdeki ortaklar tarafından sunulabilir. İşinizin ölçeğini yalnızca erişim gücünüz belirler.",
  global: [
    "Tek ürün çekirdeği: Uluslararası müşterilerde başarıyla çalışan aynı yapay zekâ ürünleri.",
    "Yerelleştirilmiş ticari duruş: Mesajı, yaklaşımı ve müzakereleri yerel pazarınıza uyarlarsınız.",
    "Çoklu gelir modelleri: Düzenli SaaS abonelikleri, aylık danışmanlıklar ve yüksek bütçeli dijital üretim projeleri.",
    "Teknik kadro maliyeti olmadan ölçeklenme: AI MARK tüm teknoloji, altyapı ve mühendislik yükünü üstlenir.",
  ],
  faqEyebrow: "SSS",
  faqTitle: "Ortakların sık sorduğu sorular.",
  faq: [
    { q: "Ortak olmak için bir başlangıç paketi satın almam gerekir mi?", a: "Hayır. Program ağ içinde pozisyon satın almaya değil, işletmelere gerçek AI MARK ürün ve hizmetlerini satmaya dayanır. Katılım tamamen ücretsizdir." },
    { q: "Teknik teslimatı ve geliştirmeyi kendim mi yapmalıyım?", a: "Hayır. Ortak ilişkileri kurar ve satışı gerçekleştirir. AI MARK ürünün kurulumu, geliştirilmesi ve teknik desteğinden sorumludur." },
    { q: "Kendi ortak ekibimi kurabilir miyim?", a: "Evet. Standart model, gerçek müşteri ödemelerine bağlı olarak 5 kademe derinliğe kadar çok seviyeli ortaklık yapısını destekler." },
    { q: "Abonelik ürünleri düzenli komisyon sağlar mı?", a: "Evet. Yenilemeler dahil her uygun ödeme aynı bareme tabidir: L1 %50, L2 %15, L3 %7, L4 %5, L5 %3 (toplam %80 havuz). İlk 90 gün bu oranları değiştirmez." },
    { q: "Nasıl Regional veya Strategic Partner olabilirim?", a: "Bölgesel statü kanıtlanmış satış hacmine göre verilir. Stratejik ve Ülke ortaklıkları bağımsız ikili anlaşmalarla düzenlenir." },
  ],
  ctaEyebrow: "Başlangıç",
  ctaTitle: "Sizin pazarınız. Bizim yapay zekâ altyapımız.",
  ctaLead: "AI MARK ortağı olarak katılın, en iyi bildiğiniz sektörleri seçin ve doğrudan ulaşabileceğiniz işletmelerle hemen kazanmaya başlayın.",
  ctaButton: "AI MARK Ortağı Olun",
};
