import type { ProductVariant } from "@/components/ui/ProductUI";

export type ProductCard = {
  name: string;
  type: string;
  body: string;
  revenue: string;
  variant: ProductVariant;
  href?: string;
};

export type PartnerPageCopy = {
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  title: string;
  lead: string;
  note: string;
  primary: string;
  secondary: string;
  marketEyebrow: string;
  marketTitle: string;
  marketLead: string;
  market: { title: string; body: string }[];
  marketCore: string;
  productEyebrow: string;
  productTitle: string;
  productLead: string;
  products: ProductCard[];
  productCta: string;
  productionCta: string;
  howEyebrow: string;
  modelTitle: string;
  modelLead: string;
  steps: { n: string; title: string; body: string }[];
  networkEyebrow: string;
  networkTitle: string;
  networkLead: string;
  poolHeadline: string;
  poolLead: string;
  exampleTitle: string;
  exampleRows: { label: string; value: string; accent?: boolean }[];
  exampleFoot: string;
  levels: { n: string; title: string; body: string; rate: string }[];
  commissionLabel: string;
  commissionNote: string;
  statusEyebrow: string;
  statusTitle: string;
  statusLead: string;
  statuses: { tag: string; title: string; body: string }[];
  statusNote: string;
  kitEyebrow: string;
  kitTitle: string;
  kitLead: string;
  kit: string[];
  globalEyebrow: string;
  globalTitle: string;
  globalLead: string;
  global: string[];
  faqEyebrow: string;
  faqTitle: string;
  faq: { q: string; a: string }[];
  ctaEyebrow: string;
  ctaTitle: string;
  ctaLead: string;
  ctaButton: string;
};
