import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyVi: PartnerPageCopy = {
  metaTitle: "Mạng Lưới Đối Tác AI MARK — Xây Dựng Thị Trường Của Bạn",
  metaDescription: "Kinh doanh các sản phẩm AI và giải pháp kỹ thuật số cùng AI MARK. Xây dựng quan hệ khách hàng, mở rộng thị trường mới và bứt phá nhờ mạng lưới đối tác có cấu trúc bài bản.",
  eyebrow: "Mạng Lưới Đối Tác AI MARK",
  title: "Xây dựng thị trường AI tại quốc gia của bạn.",
  lead: "Phân phối các sản phẩm AI thực chiến và giải pháp số cho các doanh nghiệp trong khu vực của bạn. AI MARK cung cấp công nghệ lõi, năng lực triển khai sản phẩm và hạ tầng đối tác. Bạn tập trung xây dựng mối quan hệ và doanh số.",
  note: "50% cho bán hàng trực tiếp · Tổng quỹ thưởng đối tác toàn mạng lưới lên tới 80% · Tham gia miễn phí",
  primary: "Trở Thành Đối Tác",
  secondary: "Tìm hiểu cách hoạt động",
  marketEyebrow: "Cơ Hội Thị Trường",
  marketTitle: "Một danh mục giải pháp. Nhu cầu rộng lớn trên mọi ngành nghề.",
  marketLead: "Cơ hội kinh doanh không hề giới hạn ở một ngách hẹp. Doanh nghiệp ở bất kỳ lĩnh vực nào cũng cần vận hành, thu hút khách hàng, giao tiếp liên tục, duy trì sự hiện diện kỹ thuật số và tự động hóa quy trình.",
  market: [
    { title: "Vận hành", body: "Giao tiếp định kỳ, quản trị tri thức, phối hợp liên phòng ban và giải quyết yêu cầu khách hàng tạo ra nhu cầu vận hành liên tục." },
    { title: "Tiếp thị", body: "Mọi doanh nghiệp đều cần sự hiện diện, nội dung chất lượng, các chiến dịch hiệu quả, đối thoại khách hàng và cỗ máy tăng trưởng bền vững." },
    { title: "Phát triển số", body: "Các doanh nghiệp đang phát triển cần website cao cấp, cổng thông tin, ứng dụng di động, tích hợp hệ thống và giải pháp tùy chỉnh." },
    { title: "Tự động hóa", body: "Khi quy trình phức tạp hơn, nhu cầu về AI, tự động hóa và các hệ thống cắt giảm chi phí nhân sự thủ công ngày càng tăng cao." },
  ],
  marketCore: "Thị trường của bạn không phải một công cụ đơn lẻ. Đó là tất cả các doanh nghiệp bạn có thể tiếp cận.",
  productEyebrow: "Danh mục sản phẩm",
  productTitle: "Bốn phương thức tạo giá trị thực tế cho khách hàng.",
  productLead: "Đối tác có thể kết nối chính xác vấn đề của doanh nghiệp với giải pháp phù hợp của AI MARK, thay vì cố gắng bán một công cụ duy nhất cho một nhóm đối tượng hẹp.",
  products: [
    { name: "AI Marketing Employee", type: "ĐỊNH KỲ / SẢN PHẨM AI", body: "Hệ thống tiếp thị AI nguyên bản: nghiên cứu thị trường, chiến lược, sáng tạo nội dung, hình ảnh, phê duyệt, đăng tải tự động và tối ưu hóa liên tục.", revenue: "Doanh thu thuê bao", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "ĐỊNH KỲ / SẢN PHẨM AI", body: "Hộp thư bán hàng và chăm sóc khách hàng dựa trên cơ sở tri thức doanh nghiệp, sàng lọc khách hàng tiềm năng và chuyển giao linh hoạt cho nhân sự.", revenue: "Doanh thu thuê bao", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "ĐỊNH KỲ / SẢN PHẨM AI", body: "Nhân viên bán hàng AI hỗ trợ tư vấn, tra cứu danh mục, tính toán theo công thức giá, xuất thông số kỹ thuật và tạo báo giá thương mại chuyên nghiệp.", revenue: "Doanh thu thuê bao", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "DỰ ÁN / DỊCH VỤ B2B", body: "Website, cổng thông tin khách hàng, ứng dụng số, tích hợp API, tự động hóa và phát triển hệ thống AI theo yêu cầu cho các tổ chức quy mô lớn.", revenue: "Doanh thu dự án lớn", variant: "saas" },
  ],
  productCta: "Xem chi tiết sản phẩm",
  productionCta: "Sản Xuất Kỹ Thuật Số",
  howEyebrow: "Cách Thức Vận Hành",
  modelTitle: "Bạn bán hàng. AI MARK triển khai và vận hành.",
  modelLead: "Đối tác là cầu nối trực tiếp với thị trường. AI MARK chịu trách nhiệm toàn diện về chất lượng sản phẩm cam kết, nền tảng công nghệ và bảo trì kỹ thuật.",
  steps: [
    { n: "01", title: "Tìm kiếm doanh nghiệp", body: "Tận dụng các mối quan hệ kinh doanh, am hiểu thị trường địa phương hoặc tệp khách hàng sẵn có." },
    { n: "02", title: "Xác định nhu cầu", body: "Lựa chọn sản phẩm hoặc dịch vụ giải quyết triệt để vấn đề mà doanh nghiệp đang gặp phải." },
    { n: "03", title: "Giới thiệu AI MARK", body: "Gửi liên kết giới thiệu cá nhân của bạn, chia sẻ trang sản phẩm hoặc sắp xếp buổi làm việc trực tiếp." },
    { n: "04", title: "Chốt hợp đồng", body: "Khách hàng đăng ký sử dụng và thanh toán thông qua kênh đối tác được định danh chuẩn xác." },
    { n: "05", title: "AI MARK triển khai", body: "Cài đặt hệ thống, tích hợp kỹ thuật và hỗ trợ bảo hành do đội ngũ chuyên gia AI MARK đảm nhiệm." },
    { n: "06", title: "Mở rộng thị trường", body: "Tái tục hợp đồng, phát triển danh mục khách hàng và kết nối thêm các đối tác mới vào mạng lưới." },
  ],
  networkEyebrow: "Mạng Lưới Đối Tác",
  networkTitle: "Tập trung bán hàng trực tiếp trước. Mở rộng thu nhập mạng lưới tiếp theo.",
  networkLead: "Mạng lưới được xây dựng dựa trên các khoản thanh toán thực tế của khách hàng, không phải các lượt đăng ký ảo. 5 cấp độ cùng chia sẻ số tiền khách hàng thực tế chi trả. 80% là tổng quỹ đối tác tích lũy qua các cấp đủ điều kiện — không phải là khoản chi trả cho một đối tác đơn lẻ.",
  poolHeadline: "50% cho bán hàng trực tiếp. Quỹ thưởng toàn mạng lưới lên tới 80%.",
  poolLead: "Cấp 1 (L1) nhận 50% doanh thu tính hoa hồng. Các cấp còn lại chia sẻ 30%. Tổng cộng tạo thành quỹ mạng lưới 80%. Tỷ lệ AI Mark giữ lại là 20%.",
  exampleTitle: "Ví dụ với một đơn hàng tính hoa hồng trị giá $1.000 có mạng lưới 5 cấp đủ điều kiện",
  exampleRows: [
    { label: "Đối tác trực tiếp L1", value: "$500", accent: true },
    { label: "L2", value: "$150" },
    { label: "L3", value: "$70" },
    { label: "L4", value: "$50" },
    { label: "L5", value: "$30" },
    { label: "Quỹ đối tác (tổng cộng)", value: "$800" },
    { label: "Phần giữ lại của AI Mark", value: "$200" },
  ],
  exampleFoot: "Đối tác trực tiếp nhận $500, không phải $800. 80% là tổng giá trị tối đa trên toàn bộ mạng lưới từ L1 đến L5 khi tất cả các cấp đều đủ tiêu chuẩn.",

  renewalExampleTitle: "Cùng giao dịch $1.000 từ tháng thứ 4 (gia hạn)",
  renewalExampleRows: [
    { label: "Đối tác trực tiếp L1", value: "$200", accent: true },
    { label: "L2", value: "$50" },
    { label: "Quỹ đối tác (tổng hợp)", value: "$250" },
    { label: "Phần AI Mark giữ lại", value: "$750" },
  ],
  renewalExampleFoot: "Gia hạn không lặp lại lưới launch bonus đủ năm cấp.",
  launchBonusBadge: "Launch bonus · until 31.12.2026",
  levels: [
    { n: "L1", title: "Bán hàng trực tiếp", body: "Khách hàng do chính bạn giới thiệu và trực tiếp hoàn tất thỏa thuận.", rate: "50%" },
    { n: "L2", title: "Mạng lưới cấp 1", body: "Doanh số thanh toán từ khách hàng của các đối tác cấp 1 do bạn bảo trợ.", rate: "15%" },
    { n: "L3", title: "Mạng lưới mở rộng", body: "Doanh số thanh toán sâu hơn một cấp trong cơ cấu tổ chức của bạn.", rate: "7%" },
    { n: "L4", title: "Độ sâu thị trường", body: "Doanh số phát sinh vượt ra ngoài phạm vi mối quan hệ trực tiếp.", rate: "5%" },
    { n: "L5", title: "Độ sâu tối đa", body: "Cấp độ sâu nhất trong cơ chế hoa hồng liên kết tiêu chuẩn.", rate: "3%" },
  ],
  commissionLabel: "Chính Sách Hoa Hồng",
  commissionNote: "L1 50% / L2 15% / L3 7% / L4 5% / L5 3% trên số tiền thực thu. Tổng quỹ mạng lưới 80%.",
  statusEyebrow: "Cấp Bậc Đối Tác",
  statusTitle: "Bốn nấc thang phát triển cùng AI MARK.",
  statusLead: "Cấp bậc phản ánh kết quả kinh doanh thực tế và chiều sâu hợp tác. Đây là sự công nhận dựa trên năng lực thương mại, không thể mua bằng tiền.",
  statuses: [
    { tag: "START", title: "Partner", body: "Kinh doanh các giải pháp AI MARK, sử dụng liên kết giới thiệu, tài liệu chính thức và bắt đầu có những khách hàng đầu tiên." },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "Đối tác hoạt động ổn định với danh mục khách hàng tăng trưởng đều đặn và bước đầu xây dựng mạng lưới." },
    { tag: "MARKET", title: "Regional Partner", body: "Phát triển thị trường một khu vực hoặc quốc gia thông qua quan hệ chiến lược, điều phối bán hàng và dẫn dắt địa phương." },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "Các đại lý lớn, nhà phân phối và kênh B2B doanh nghiệp. Đối tác Quốc gia và Đối tác Chiến lược được quy định bằng thỏa thuận riêng biệt." },
  ],
  statusNote: "Cấp bậc theo hiệu quả kinh doanh",
  kitEyebrow: "Công Cụ Cho Đối Tác",
  kitTitle: "Hạ tầng sẵn sàng cho đối tác ngay sau khi đăng ký.",
  kitLead: "Liên kết giới thiệu độc quyền, Partner Dashboard, trang sản phẩm công khai, bộ nhận diện thương hiệu và các kênh hỗ trợ qua Telegram, WhatsApp, Messenger, email.",
  kit: [
    "Liên kết giới thiệu cá nhân và mã định danh Partner ID riêng",
    "Partner Dashboard theo dõi chi tiết doanh số, hoa hồng và lịch sử thanh toán minh bạch",
    "Trang giới thiệu sản phẩm trực tuyến gắn mã tiếp thị liên kết của bạn",
    "Tài liệu thương hiệu chuẩn mực và các bản trình bày giải pháp cho khách hàng",
    "Định danh khách hàng chuẩn xác trên biểu mẫu liên hệ, đăng ký đối tác và cổng thanh toán /pay",
    "Cơ sở dữ liệu thông số kỹ thuật và tính năng sản phẩm cập nhật trong Partner Hub",
    "Kênh hỗ trợ nhanh chóng: Telegram, WhatsApp, Messenger và email",
  ],
  globalEyebrow: "Mở Rộng Toàn Cầu",
  globalTitle: "Chọn thị trường của bạn. AI MARK bảo đảm công nghệ.",
  globalLead: "Cùng một danh mục sản phẩm cốt lõi đã được kiểm chứng có thể được triển khai bởi các đối tác khác nhau tại nhiều quốc gia và ngành nghề. Quy mô doanh nghiệp hoàn toàn do tầm tiếp cận của bạn quyết định.",
  global: [
    "Công nghệ cốt lõi đồng nhất: Các sản phẩm AI ưu việt đã chứng minh hiệu quả trên các thị trường quốc tế.",
    "Bản địa hóa thương mại: Đối tác linh hoạt điều chỉnh thông điệp, văn hóa và cách đàm phán phù hợp thị trường sở tại.",
    "Đa dạng nguồn doanh thu: Thuê bao SaaS định kỳ hàng tháng, hợp đồng dịch vụ duy trì và các dự án phần mềm quy mô lớn.",
    "Tăng trưởng không gánh nặng nhân sự công nghệ: AI MARK phụ trách toàn bộ hạ tầng kỹ thuật, nghiên cứu và phát triển.",
  ],
  faqEyebrow: "Câu Hỏi Thường Gặp",
  faqTitle: "Giải đáp thắc mắc của đối tác.",
  faq: [
    { q: "Tôi có cần mua gói sản phẩm ban đầu để trở thành đối tác không?", a: "Không. Chương trình xây dựng xoay quanh việc kinh doanh sản phẩm và giải pháp thực tế của AI MARK cho doanh nghiệp, không bán vị trí hay yêu cầu phí gia nhập. Đăng ký hoàn toàn miễn phí." },
    { q: "Tôi có phải tự tay thực hiện việc lập trình và triển khai kỹ thuật không?", a: "Không. Đối tác tập trung vào việc tạo dựng mối quan hệ và bán hàng. AI MARK chịu trách nhiệm triển khai, cài đặt và bảo đảm vận hành kỹ thuật." },
    { q: "Tôi có thể xây dựng đội ngũ đối tác cấp dưới không?", a: "Có. Mô hình tiêu chuẩn hỗ trợ cơ cấu liên kết đa cấp độ dựa trên doanh thu khách hàng thực tế, với độ sâu lên tới 5 tầng." },
    { q: "Các sản phẩm thuê bao định kỳ có mang lại hoa hồng tái tục không?", a: "Có. Khoản thanh toán đầu dùng launch bonus (đến 31.12.2026) hoặc lưới chuẩn từ 01.01.2027. Từ khoản thứ 2, gia hạn chỉ L1 20% + L2 5%." },
    { q: "Làm thế nào để trở thành Regional hay Strategic Partner?", a: "Cấp Regional được xét duyệt dựa trên doanh số thực tế đã được xác minh và vị thế dẫn dắt. Đối tác Chiến lược và Đại diện Quốc gia được thiết lập theo hợp đồng kinh tế riêng biệt." },
  ],
  ctaEyebrow: "Khởi Đầu Ngay",
  ctaTitle: "Thị trường của bạn. Nền tảng AI của chúng tôi.",
  ctaLead: "Gia nhập mạng lưới đối tác AI MARK, chọn các lĩnh vực kinh doanh bạn am hiểu nhất và bắt đầu tiếp cận những doanh nghiệp ngay trong tầm tay.",
  ctaButton: "Trở Thành Đối Tác AI MARK",
};
