import { PRODUCT_PATHS } from "@/lib/products";
import type { PartnerPageCopy } from "./types";

export const copyZh: PartnerPageCopy = {
  metaTitle: "AI MARK 合作伙伴网络 — 开拓您的商业市场",
  metaDescription: "与 AI MARK 携手销售前沿 AI 产品与数字化解决方案。建立深度客户关系，拓展全新市场，依托结构化合作网络实现规模化增长。",
  eyebrow: "AI MARK 合作伙伴网络",
  title: "在您的国家开拓 AI 商业市场。",
  lead: "向您所在区域的企业提供真正的 AI 落地产品与数字基础设施。AI MARK 提供核心技术引擎、产品交付保障与完善的合作伙伴支持。您专注于商务连接与成交。",
  note: "直接销售立享 50% · 全网最高累计 80% 合作伙伴奖金池 · 零门槛免费加入",
  primary: "成为合作伙伴",
  secondary: "查看运作模式",
  marketEyebrow: "广阔市场",
  marketTitle: "一套统一产品矩阵。跨行业的广阔市场需求。",
  marketLead: "商业机遇绝不局限于单一细分领域。任何行业的企业都需要日常运营、客户获取、深度沟通、数字化呈现以及流程自动化。",
  market: [
    { title: "日常运营", body: "日常业务沟通、知识库管理、跨团队协同与客户咨询，产生着持续而稳定的运营刚需。" },
    { title: "营销获客", body: "每家企业都需要品牌曝光、高质量内容产出、精准广告营销与可复制的稳健增长引擎。" },
    { title: "数字研发", body: "发展中企业对高端官方网站、客户门户、业务系统、第三方集成与定制化数字资产需求旺盛。" },
    { title: "流程自动化", body: "随着业务链条复杂度提升，企业对 AI 智能体、无缝自动化与降低人工边际成本的需求爆发式增长。" },
  ],
  marketCore: "您的目标市场不仅是一款工具，而是您能触达的所有实体企业。",
  productEyebrow: "产品组合",
  productTitle: "四种为客户创造核心价值的途径。",
  productLead: "合作伙伴可以将企业的痛点精准匹配到 AI MARK 对应的解决方案，而不是单一产品走天下。",
  products: [
    { name: "AI Marketing Employee", type: "持续订阅 / AI 核心产品", body: "原生 AI 营销全流程：市场调研、策略制定、爆款文案、视觉创意、人工审核、自动发布与数据追踪优化。", revenue: "持续订阅分成", variant: "aime", href: PRODUCT_PATHS.aime },
    { name: "AI Business Assistant", type: "持续订阅 / AI 核心产品", body: "基于企业私有知识库的智能客服与销售收件箱，精准筛选意向线索，必要时无缝转接人工坐席。", revenue: "持续订阅分成", variant: "assistant", href: PRODUCT_PATHS.assistant },
    { name: "SHOWROOM AI / AI Sales Agent", type: "持续订阅 / AI 核心产品", body: "智能销售专家：负责客户导购对话、目录筛选、算价公式、定制规格说明书与专业商务报价单生成。", revenue: "持续订阅分成", variant: "showroom", href: PRODUCT_PATHS.showroom },
    { name: "Digital Production & AI Engineering", type: "定制项目 / B2B 服务", body: "高并发网站、客户门户平台、核心业务系统、跨平台集成与企业级定制 AI 引擎开发。", revenue: "大型项目分成", variant: "saas" },
  ],
  productCta: "了解产品详情",
  productionCta: "数字工程研发",
  howEyebrow: "运作流程",
  modelTitle: "您负责拓客销售。AI MARK 负责技术交付。",
  modelLead: "合作伙伴是本地市场的信任桥梁与商务接口。AI MARK 对交付质量、系统稳定性和底层技术标准负全责。",
  steps: [
    { n: "01", title: "发掘企业线索", body: "调动您的商业人脉、本地商会资源或现有合作客户群。" },
    { n: "02", title: "匹配业务痛点", body: "针对企业当前面临的效率或获客瓶颈，挑选最合适的 AI MARK 产品或方案。" },
    { n: "03", title: "引荐 AI MARK", body: "发送您的专属推荐链接、产品页面，或直接促成双方商务沟通。" },
    { n: "04", title: "达成商业成交", body: "客户通过带归因追踪的专属渠道完成订单支付与系统签约。" },
    { n: "05", title: "系统交付与运维", body: "技术环境部署、参数调优、员工培训与日常维护均由 AI MARK 专业团队执行。" },
    { n: "06", title: "扩大市场规模", body: "持续复购与转介绍，拓展客户矩阵，并在团队中招募更多合资格伙伴。" },
  ],
  networkEyebrow: "合作网络",
  networkTitle: "立足个人直销。裂变网络收益。",
  networkLead: "合作网络建立在客户实际支付的资金流水上，而非虚假注册量。合格的 5 个层级共同分享客户实付金额。80% 为所有合资格层级的最高累计奖金池，绝非单人独享。",
  poolHeadline: "直接销售即享 50%。全网最高 80% 累计合作伙伴奖金池。",
  poolLead: "第 1 级（L1）独享可分润金额的 50%。其余层级共同分享 30%。全网累计奖金池高达 80%。AI Mark 平台保留份额为 20%。",
  exampleTitle: "以一笔 1,000 美元且网络各级均合资格的实际成交为例",
  exampleRows: [
    { label: "L1 直推合作伙伴", value: "$500", accent: true },
    { label: "L2 级合作伙伴", value: "$150" },
    { label: "L3 级合作伙伴", value: "$70" },
    { label: "L4 级合作伙伴", value: "$50" },
    { label: "L5 级合作伙伴", value: "$30" },
    { label: "合作伙伴奖金池（累计）", value: "$800" },
    { label: "AI Mark 平台保留份额", value: "$200" },
  ],
  exampleFoot: "直推伙伴实际获得 $500，而非 $800。80% 是当 L1 至 L5 每一层均满足资格时的全网总奖金池上限。",
  levels: [
    { n: "L1", title: "直接销售", body: "您亲自发掘并促成签约付款的企业客户。", rate: "50%" },
    { n: "L2", title: "第一级伙伴网络", body: "您直接引荐的第一级合作伙伴所促成的客户付款流水。", rate: "15%" },
    { n: "L3", title: "扩展伙伴网络", body: "在合作组织中向下延伸一级的实际客户付款提成。", rate: "7%" },
    { n: "L4", title: "深度市场网络", body: "超越您直接认知圈层的裂变市场成交提成。", rate: "5%" },
    { n: "L5", title: "最大网络深度", body: "标准联盟提成规则下所覆盖的最深一层收益。", rate: "3%" },
  ],
  commissionLabel: "佣金政策",
  commissionNote: "按客户实际净到账金额执行：L1 50% / L2 15% / L3 7% / L4 5% / L5 3%。全网奖金池 80%。",
  statusEyebrow: "合作级别",
  statusTitle: "与 AI MARK 共同成长的四个阶段。",
  statusLead: "合作伙伴级别真实反映您的商业产出与合作紧密度。这是商业成就勋章，不可花钱购买。",
  statuses: [
    { tag: "START", title: "Partner", body: "推广 AI MARK 核心产品，获取专属推广链接，使用官方物料开发首批客户。" },
    { tag: "ACTIVE SALES", title: "Growth Partner", body: "业绩持续稳定的活跃业务精英，拥有稳步增长的客户资产和团队网络雏形。" },
    { tag: "MARKET", title: "Regional Partner", body: "负责特定国家或重点区域的市场深耕，统筹本地合作网络与重点行业攻坚。" },
    { tag: "ENTERPRISE", title: "Strategic Partner", body: "大型代理商、系统集成商及 B2B 核心渠道。国家总代与战略级合作另设双边专属协议。" },
  ],
  statusNote: "按实际业绩晋升",
  kitEyebrow: "赋能工具箱",
  kitTitle: "合作伙伴即刻拥有的赋能支持。",
  kitLead: "专属推广链接、Partner Dashboard 仪表盘、全套产品落地页、品牌视觉规范，以及覆盖 Telegram、WhatsApp、Messenger 和邮件的专属支持通道。",
  kit: [
    "专属推广推荐链接与 Partner ID 唯一身份标识",
    "Partner Dashboard：实时查看客户订单、收益明细与提现记录",
    "与您的推广标识自动绑定的多语言产品详情落地页",
    "官方高清品牌资产、专业演示文稿与客户沟通指南",
    "全链路商机追踪：精准归因联系表单、伙伴注册与 /pay 支付终端",
    "内置于 Partner Hub 的权威产品功能说明与商业参数库",
    "多渠道即时服务：Telegram、WhatsApp、Messenger 及官方邮箱",
  ],
  globalEyebrow: "全球化布局",
  globalTitle: "选择您的主战场。AI MARK 提供硬核技术。",
  globalLead: "同一套成熟的 AI 产品矩阵，可由不同伙伴在不同国家及垂直行业灵活推开。您的商业天花板取决于您的行动力与人脉圈。",
  global: [
    "统一产品引擎：历经验证的高性能企业级 AI 产品直接服务全球客户。",
    "本地化商务打法：由您自主把控当地商务公关、语言偏好与行业商务谈判。",
    "多元化变现途径：涵盖高黏性 SaaS 订阅、月度咨询运维及大型定制数字化工程。",
    "无需自建研发团队：AI MARK 全面承担软件架构、大模型接入与工程运维重任。",
  ],
  faqEyebrow: "常见问题",
  faqTitle: "合作伙伴核心答疑。",
  faq: [
    { q: "成为合作伙伴需要购买入门礼包或会员包吗？", a: "不需要。该计划完全围绕帮助实体企业导入真正的 AI 解决方案并产生实付流水展开，严禁出售加盟资格。加入完全免费。" },
    { q: "我需要亲自负责技术研发与产品交付吗？", a: "不需要。伙伴的核心工作是商务接洽与信任建立。AI MARK 专业团队全面承担系统部署、产品上线与后期技术保障。" },
    { q: "我可以组建自己的伙伴业务团队吗？", a: "可以。标准政策支持基于客户实际付费流水的最高 5 级推荐奖励结构，透明公平。" },
    { q: "客户续费订阅可以持续获得佣金提成吗？", a: "可以。客户在系统中的每一笔合资格续费，均严格按照 L1 50%、L2 15%、L3 7%、L4 5%、L5 3%（全网 80% 奖金池）结算。前 90 天不设费率下调。" },
    { q: "如何晋升为 Regional 或 Strategic Partner？", a: "区域级（Regional）伙伴依据稳定的成交总额与本地行业影响力评审授予。战略合作与国家级代理遵循独立的商业合同条款。" },
  ],
  ctaEyebrow: "立即启航",
  ctaTitle: "您的商业版图。我们的 AI 底座。",
  ctaLead: "立即注册成为 AI MARK 合作伙伴，锁定您最熟悉的优势行业，从身边触手可及的企业客户开始开启商业变现。",
  ctaButton: "成为 AI MARK 合作伙伴",
};
